'use client';
import Link from 'next/link';
import { use, useEffect, useMemo, useState } from 'react';
import { useLanguage } from '@/components/providers/LanguageProvider';
import { Badge, Button, ErrorState, handleTabListKeyDown, InlineAlert, LoadingState, PageShell } from '@/components/ui';
import { createInstrumentDraft, getInstruments, getInstrumentVersion, saveInstrumentDraft, submitInstrumentReview, validateInstrument } from './api';
import { isEditable, latestVersion, statusTone, validateDraft } from './model';
import { PreviewPanel } from './PreviewPanel';
import { QuestionEditor } from './QuestionEditor';
import type { Instrument, InstrumentDetail, QuestionDraft, ValidationResponse } from './types';
import type { Messages } from '@/lib/i18n/messages';

type Tab='overview'|'questions'|'scoring'|'source';
export function InstrumentDetailPage({params}:{params:Promise<{instrumentId:string}>}){const {instrumentId}=use(params);const {language,text}=useLanguage();const copy=text.instruments;const [instrument,setInstrument]=useState<Instrument|null>(null);const [detail,setDetail]=useState<InstrumentDetail|null>(null);const [questions,setQuestions]=useState<QuestionDraft[]>([]);const [selected,setSelected]=useState(0);const [tab,setTab]=useState<Tab>('overview');const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [saving,setSaving]=useState(false);const [mutationError,setMutationError]=useState('');const [preview,setPreview]=useState(false);const [validation,setValidation]=useState<ValidationResponse|null>(null);const [dirty,setDirty]=useState(false);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();getInstruments(controller.signal).then(async(result)=>{const found=result.instruments.find((item)=>item.instrument_id===instrumentId);if(!found)throw new Error('not-found');setInstrument(found);setError(false);const version=latestVersion(found);if(!version)throw new Error('no-version');const loaded=await getInstrumentVersion(version.instrument_version_id,controller.signal);setDetail(loaded);setQuestions(loaded.questions);setDirty(false);setLoading(false)}).catch((caught)=>{if(!(caught instanceof DOMException&&caught.name==='AbortError')){setError(true);setLoading(false)}});return()=>controller.abort()},[instrumentId,refresh]);
 useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);
 const editable=detail?isEditable(detail):false;const localIssues=useMemo(()=>validateDraft(questions),[questions]);const categoryLabel=(value:string)=>copy.dimensions[value]??value;
 const updateQuestions=(value:QuestionDraft[])=>{setQuestions(value);setDirty(true);setValidation(null)};
 const save=async()=>{if(!detail||localIssues.length)return;setSaving(true);setMutationError('');try{const saved=await saveInstrumentDraft(detail.version.instrument_version_id,questions,detail.version.definition_revision);setDetail(saved);setQuestions(saved.questions);setDirty(false)}catch{setMutationError(copy.errors.save)}finally{setSaving(false)}};
 const createDraft=async()=>{if(!instrument)return;setMutationError('');try{const created=await createInstrumentDraft(instrument.instrument_id);setDetail(created);setQuestions(created.questions);setTab('questions');setRefresh((x)=>x+1)}catch{setMutationError(copy.errors.version)}};
 const runValidation=async()=>{if(!detail)return;setMutationError('');try{setValidation(await validateInstrument(detail.version.instrument_version_id))}catch{setMutationError(copy.errors.validate)}};
 const submitReview=async()=>{if(!detail||dirty)return;setMutationError('');try{await submitInstrumentReview(detail.version.instrument_version_id,detail.version.definition_revision);setRefresh(x=>x+1)}catch{setMutationError(copy.errors.review)}};
 if(loading)return <LoadingState fullPage label={text.common.loading}/>;if(error||!detail||!instrument)return <ErrorState title={copy.errors.title} message={copy.errors.load} retry={()=>setRefresh((x)=>x+1)} retryLabel={text.common.retry}/>;
 const version=detail.version;return <PageShell actions={<><Link className="button button-secondary" href="/instruments" onClick={(e)=>{if(dirty&&!confirm(copy.unsaved))e.preventDefault()}}>{copy.actions.back}</Link><Button variant="secondary" onClick={()=>setPreview(true)}>{copy.actions.preview}</Button>{editable&&<Button loading={saving} disabled={localIssues.length>0} onClick={save}>{saving?copy.actions.saving:copy.actions.save}</Button>}{version.instrument_kind==='custom'&&version.status!=='draft'&&<Button onClick={createDraft}>{copy.actions.newVersion}</Button>}</>}>
 <header className="instrument-detail-head"><div><div className="detail-title-line"><h1>{version.name}</h1><Badge tone={version.instrument_kind==='standard'?'info':'neutral'}>{copy.type[version.instrument_kind]}</Badge><Badge tone={statusTone(version.status)}>{copy.status[version.status]}</Badge></div><p>{instrument.description}</p></div><dl><div><dt>{copy.fields.version}</dt><dd>v{version.version_number}</dd></div><div><dt>{copy.fields.language}</dt><dd>{version.language??'—'}</dd></div><div><dt>{copy.fields.questions}</dt><dd>{questions.filter((q)=>q.active).length}</dd></div></dl></header>
 {version.instrument_kind==='standard'&&<InlineAlert title={copy.detail.protected}>{copy.detail.standardScoring}</InlineAlert>}{version.status!=='draft'&&<InlineAlert>{copy.detail.immutable}</InlineAlert>}{editable&&<InlineAlert>{copy.detail.atomic} {copy.detail.concurrency}</InlineAlert>}{mutationError&&<InlineAlert tone="danger">{mutationError}</InlineAlert>}
 {editable&&<section className="instrument-card"><h2>{copy.fields.validation}</h2><p>{detail.reviews?.[0]?.status??copy.validation.notSubmitted}</p><Button disabled={dirty||localIssues.length>0||detail.reviews?.[0]?.status==='pending'} onClick={submitReview}>{copy.actions.requestValidation}</Button></section>}
 <nav className="instrument-tabs" role="tablist" aria-label={copy.title} onKeyDown={handleTabListKeyDown}>{(['overview','questions','scoring','source'] as Tab[]).map((item)=><button type="button" role="tab" key={item} id={`instrument-tab-${item}`} aria-controls={`instrument-panel-${item}`} aria-selected={tab===item} tabIndex={tab===item?0:-1} className={tab===item?'active':''} onClick={()=>setTab(item)}>{copy.detail[item]}</button>)}</nav>
 <div id={`instrument-panel-${tab}`} role="tabpanel" aria-labelledby={`instrument-tab-${tab}`}>
 {tab==='overview'&&<div className="instrument-summary-grid"><section className="instrument-card"><h2>{copy.detail.overview}</h2><dl className="summary-list"><div><dt>{copy.fields.name}</dt><dd>{version.name}</dd></div><div><dt>{copy.fields.type}</dt><dd>{copy.type[version.instrument_kind]}</dd></div><div><dt>{copy.fields.status}</dt><dd>{copy.status[version.status]}</dd></div><div><dt>{copy.fields.dimensions}</dt><dd>{[...new Set(questions.map((q)=>q.category))].map(categoryLabel).join(', ')||'—'}</dd></div></dl></section><section className="instrument-card"><h2>{copy.fields.validation}</h2><Badge tone="warning">{copy.validation.notSubmitted}</Badge><p>{copy.validation.unavailableBody}</p><Button disabled>{copy.actions.requestValidation}</Button></section><section className="instrument-card"><h2>{copy.validation.serverCheck}</h2><p>{validation?(validation.publishable?copy.validation.publishable:copy.validation.blocked):copy.actions.validate}</p>{validation?.issues.map((issue)=><p className="validation-issue" key={issue}>• {issue}</p>)}<Button variant="secondary" disabled={dirty||version.status!=='draft'} onClick={runValidation}>{copy.actions.validate}</Button></section></div>}
 {tab==='questions'&&<section className="instrument-card question-card"><QuestionEditor questions={questions} selected={selected} onSelect={setSelected} onChange={updateQuestions} editable={editable} copy={copy} categoryLabel={categoryLabel}/>{editable&&localIssues.length>0&&<InlineAlert tone="warning">{copy.builder.questionsIncomplete}</InlineAlert>}</section>}
 {tab==='scoring'&&<ScoringPanel detail={detail} copy={copy} categoryLabel={categoryLabel}/>} 
 {tab==='source'&&<SourcePanel instrument={instrument} detail={detail} copy={copy} language={language}/>} 
 </div>
 <PreviewPanel open={preview} onOpenChange={setPreview} title={copy.preview.title} privacy={copy.preview.privacy} answer={copy.preview.answer} close={copy.preview.close} questions={questions}/>
 </PageShell>}

function ScoringPanel({detail,copy,categoryLabel}:{detail:InstrumentDetail;copy:Messages['instruments'];categoryLabel:(value:string)=>string}){const config=detail.version.scoring_config;const bands=config?.severity_bands as Record<string,Array<{label:string;min:number;max:number}>>|undefined;return <div className="scoring-layout"><section className="instrument-card"><h2>{copy.detail.scoring}</h2>{!config?<p>{copy.detail.noScoring}</p>:<><div className="score-flow"><span>{copy.fields.option}</span><b>→</b><span>{copy.fields.score}</span><b>→</b><span>{copy.fields.dimensions}</span>{typeof config.standardization_multiplier==='number'&&<><b>→</b><span>× {config.standardization_multiplier}</span></>}</div><p>{detail.version.instrument_kind==='standard'?copy.detail.standardScoring:copy.detail.customScoring}</p></>}</section>{bands&&<section className="instrument-card"><h2>{copy.detail.scoring}</h2><div className="threshold-tables">{Object.entries(bands).map(([category,ranges])=><table key={category}><caption>{categoryLabel(category)}</caption><thead><tr><th>{copy.fields.status}</th><th>{copy.fields.minimum}</th><th>{copy.fields.maximum}</th></tr></thead><tbody>{ranges.map((range)=><tr key={range.label}><td>{range.label}</td><td>{range.min}</td><td>{range.max}</td></tr>)}</tbody></table>)}</div></section>}</div>}
function SourcePanel({instrument,detail,copy,language}:{instrument:Instrument;detail:InstrumentDetail;copy:Messages['instruments'];language:'id'|'en'}){const p=instrument.provenance;return <div className="instrument-summary-grid"><section className="instrument-card"><h2>{copy.detail.source}</h2><dl className="summary-list"><div><dt>{copy.fields.type}</dt><dd>{copy.type[instrument.instrument_kind]}</dd></div><div><dt>{copy.fields.adaptationSource}</dt><dd>{String(p.source_adaptation??copy.notAvailable)}</dd></div><div><dt>{copy.fields.originalReference}</dt><dd>{String(p.original_reference??copy.notAvailable)}</dd></div><div><dt>{copy.fields.sourceRelationship}</dt><dd>{instrument.derived_from_instrument_id?copy.source.derived:instrument.instrument_kind==='standard'?copy.source.canonical:copy.source.independent}</dd></div></dl></section><section className="instrument-card"><h2>{copy.detail.audit}</h2><dl className="summary-list"><div><dt>{copy.fields.created}</dt><dd>{formatDate(detail.version.created_at,language)} · {detail.version.created_by_name??copy.notAvailable}</dd></div><div><dt>{copy.fields.updated}</dt><dd>{formatDate(detail.version.updated_at,language)} · {detail.version.updated_by_name??copy.notAvailable}</dd></div><div><dt>{copy.fields.published}</dt><dd>{detail.version.published_at?`${formatDate(detail.version.published_at,language)} · ${detail.version.published_by_name??copy.notAvailable}`:'—'}</dd></div></dl></section><section className="instrument-card version-history"><h2>{copy.fields.version}</h2>{instrument.versions.map((version)=><div key={version.instrument_version_id}><strong>v{version.version_number}</strong><Badge tone={statusTone(version.status)}>{copy.status[version.status]}</Badge><time>{formatDate(version.updated_at,language)}</time></div>)}</section></div>}
function formatDate(value:string,language:'id'|'en'){return new Intl.DateTimeFormat(language==='id'?'id-ID':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
