'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useLanguage } from '@/components/providers/LanguageProvider';
import { Badge, Button, InlineAlert, PageShell } from '@/components/ui';
import { addQuestion, CATEGORIES, localDraftCompleteness, newLocalDraft } from './model';
import { PreviewPanel } from './PreviewPanel';
import { QuestionEditor } from './QuestionEditor';
import type { LocalInstrumentDraft } from './types';

export function NewInstrumentBuilder(){const {language,text}=useLanguage();const copy=text.instruments;const [draft,setDraft]=useState<LocalInstrumentDraft>(()=>newLocalDraft());const [step,setStep]=useState(0);const [selected,setSelected]=useState(0);const [preview,setPreview]=useState(false);const dirty=!!draft.name||!!draft.description||draft.dimensions.length>0||draft.questions.length>0;useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);const complete=localDraftCompleteness(draft);const labels=copy.builder.steps;const stepKeys=['metadata','dimensions','questions','review'] as const;const categoryLabel=(value:string)=>({depression:language==='id'?'Depresi':'Depression',anxiety:language==='id'?'Kecemasan':'Anxiety',stress:language==='id'?'Stres':'Stress'} as Record<string,string>)[value]??value;return <PageShell title={copy.builder.title} actions={<><Link className="button button-secondary" href="/instruments" onClick={(e)=>{if(dirty&&!confirm(copy.unsaved))e.preventDefault()}}>{copy.actions.back}</Link><Button variant="secondary" onClick={()=>setPreview(true)}>{copy.actions.preview}</Button></>}><InlineAlert tone="warning" title={copy.notAvailable}>{copy.builder.localNotice}</InlineAlert><nav className="builder-steps" aria-label={copy.builder.title}>{stepKeys.map((key,index)=><button type="button" key={key} className={step===index?'active':''} onClick={()=>setStep(index)}><b>{index+1}</b><span>{labels[key]}</span></button>)}</nav><section className="instrument-card builder-card">
 {step===0&&<div className="instrument-form-grid"><label><span>{copy.fields.name}</span><input value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></label><label><span>{copy.fields.language}</span><input value={draft.language} disabled/></label><label className="field-wide"><span>{copy.fields.description}</span><textarea rows={5} value={draft.description} onChange={(e)=>setDraft({...draft,description:e.target.value})}/></label><p className="field-wide form-note">{copy.builder.purpose}</p></div>}
 {step===1&&<><p className="section-note">{copy.builder.dimensionsHelp}</p><div className="dimension-picker">{CATEGORIES.map((category)=><label key={category}><input type="checkbox" checked={draft.dimensions.includes(category)} onChange={(e)=>setDraft({...draft,dimensions:e.target.checked?[...draft.dimensions,category]:draft.dimensions.filter((x)=>x!==category)})}/><span>{categoryLabel(category)}</span></label>)}</div><InlineAlert>{copy.builder.scoringHelp}</InlineAlert></>}
 {step===2&&<QuestionEditor questions={draft.questions} selected={selected} onSelect={setSelected} onChange={(questions)=>setDraft({...draft,questions})} editable copy={copy} categoryLabel={categoryLabel}/>} 
 {step===3&&<div className="review-grid"><section><h2>{draft.name||copy.fields.name}</h2><p>{draft.description||copy.fields.description}</p><dl><div><dt>{copy.fields.language}</dt><dd>{draft.language}</dd></div><div><dt>{copy.fields.dimensions}</dt><dd>{draft.dimensions.map(categoryLabel).join(', ')||'—'}</dd></div><div><dt>{copy.fields.questions}</dt><dd>{draft.questions.length}</dd></div></dl></section><section><h2>{copy.fields.validation}</h2><Status ok={complete.metadata} label={complete.metadata?labels.metadata:copy.builder.metadataIncomplete}/><Status ok={complete.dimensions} label={complete.dimensions?labels.dimensions:copy.builder.dimensionsIncomplete}/><Status ok={complete.questions} label={complete.questions?labels.questions:copy.builder.questionsIncomplete}/><InlineAlert tone="warning">{copy.builder.reviewHelp}</InlineAlert></section></div>}
 <footer className="builder-actions"><Button variant="secondary" disabled={step===0} onClick={()=>setStep((x)=>x-1)}>{copy.actions.previous}</Button>{step===2&&<Button variant="secondary" onClick={()=>{setDraft({...draft,questions:addQuestion(draft.questions)});setSelected(draft.questions.length)}}>+ {copy.actions.addQuestion}</Button>}<span/><Button disabled={step===3} onClick={()=>setStep((x)=>x+1)}>{copy.actions.next}</Button>{step===3&&<><Button disabled>{copy.actions.save}</Button><Button disabled>{copy.actions.requestValidation}</Button></>}</footer></section><PreviewPanel open={preview} onOpenChange={setPreview} title={copy.preview.title} privacy={copy.preview.privacy} answer={copy.preview.answer} close={copy.preview.close} questions={draft.questions}/></PageShell>}
function Status({ok,label}:{ok:boolean;label:string}){return <p className="review-status"><Badge tone={ok?'success':'warning'}>{ok?'✓':'!'}</Badge><span>{label}</span></p>}
