import test from 'node:test';
import assert from 'node:assert/strict';
import { academicComparison, aggregate, applyPreset, insights, makeReportConfiguration, parseReportConfiguration, sanitizeForStructure, severityByCategory } from './model.ts';
import type { AnalyticsResponse } from './types.ts';

const data: AnalyticsResponse = { mode:'faculty',date_from:'2026-09-01',date_to:'2026-09-30',selected_scopes:[],assessment_trend:[],category_trends:[],attention_counts:[{scope_id:null,scope_label:'UNDIP',signal_type:'safety',count:2}],severity_distribution:[{scope_id:'a',scope_label:'A',severity:'minimal',count:8},{scope_id:'a',scope_label:'A',severity:'severe',count:2},{scope_id:'b',scope_label:'B',severity:'severe',count:4}],category_severity_distribution:[{scope_id:null,scope_label:'UNDIP',category:'depression',severity:'normal',count:3}],counseling_utilization:[{scope_id:null,scope_label:'UNDIP',status:'completed',count:5},{scope_id:null,scope_label:'UNDIP',status:'confirmed',count:3}] };
test('aggregate keeps assessment and counseling populations distinct',()=>assert.deepEqual(aggregate(data),{assessmentTotal:14,severe:6,highRiskPercent:43,counselingTotal:8,completed:5,signals:2}));
test('academic comparison derives severe proportions from backend labels',()=>assert.deepEqual(academicComparison(data),[{label:'A',total:10,high:2,percent:20},{label:'B',total:4,high:4,percent:100}]));
test('dimension distribution does not recalculate clinical severity',()=>assert.equal(severityByCategory(data)[0].values[0].severity,'normal'));
test('faculty changes remove incompatible units',()=>{ const result=sanitizeForStructure({...applyPreset({dateFrom:'',dateTo:'',preset:'custom',compareBy:'faculty',facultyIds:['f'],academicUnitIds:['u']},'30days',new Date('2026-10-03T00:00:00Z')),academicUnitIds:['wrong']},{faculties:[{faculty_id:'f',code:null,name:'F',active:true}],academicUnits:[{academic_unit_id:'u',faculty_id:'f',faculty_name:'F',code:null,name:'U',unit_type:'study_program',active:true}]}); assert.deepEqual(result.academicUnitIds,[]);});
test('report configuration parser rejects malformed input',()=>assert.equal(parseReportConfiguration('{bad'),null));
test('report configuration keeps only supported aggregate sections',()=>{const config=makeReportConfiguration({dateFrom:'2026-09-01',dateTo:'2026-09-30',preset:'custom',compareBy:'faculty',facultyIds:['f'],academicUnitIds:[]},['summary','counseling']);const parsed=parseReportConfiguration(JSON.stringify(config));assert.deepEqual(parsed?.sections,['summary','counseling']);assert.equal(JSON.stringify(parsed).includes('student'),false);});
test('insights are deterministic in both dashboard languages',()=>{assert.equal(insights(data,'id').length,4);assert.match(insights(data,'en')[2],/Service Utilization/);});
