'use client';

import { useEffect, useId, useRef, useState, type ReactNode } from 'react';

export interface DropdownItem { label: string; onSelect: () => void; danger?: boolean; icon?: ReactNode; disabled?: boolean }
export function DropdownMenu({ trigger, label, items, align = 'end' }: { trigger: ReactNode; label: string; items: DropdownItem[]; align?: 'start' | 'end' }) {
  const [open, setOpen] = useState(false); const wrapper = useRef<HTMLDivElement>(null); const triggerRef = useRef<HTMLButtonElement>(null); const menuRef = useRef<HTMLDivElement>(null); const id = useId();
  useEffect(() => { if (!open) return; const outside = (event: PointerEvent) => { if (!wrapper.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('pointerdown', outside); return () => document.removeEventListener('pointerdown', outside); }, [open]);
  const focusItem = (index: number) => menuRef.current?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')[index]?.focus();
  return <div className="dropdown" ref={wrapper}><button ref={triggerRef} className="dropdown-trigger" aria-label={label} aria-haspopup="menu" aria-expanded={open} aria-controls={open ? id : undefined} onClick={() => setOpen((value) => !value)} onKeyDown={(event) => { if (event.key === 'ArrowDown') { event.preventDefault(); setOpen(true); window.requestAnimationFrame(() => focusItem(0)); } }}>{trigger}</button>{open && <div ref={menuRef} id={id} className={`dropdown-menu dropdown-${align}`} role="menu" aria-label={label} onKeyDown={(event) => { const buttons = Array.from(menuRef.current?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]') ?? []); const index = buttons.indexOf(document.activeElement as HTMLButtonElement); if (event.key === 'Escape') { event.preventDefault(); setOpen(false); triggerRef.current?.focus(); } else if (event.key === 'ArrowDown') { event.preventDefault(); buttons[(index + 1) % buttons.length]?.focus(); } else if (event.key === 'ArrowUp') { event.preventDefault(); buttons[(index - 1 + buttons.length) % buttons.length]?.focus(); } else if (event.key === 'Home') { event.preventDefault(); buttons[0]?.focus(); } else if (event.key === 'End') { event.preventDefault(); buttons.at(-1)?.focus(); } }}>{items.map((item) => <button key={item.label} role="menuitem" disabled={item.disabled} className={item.danger ? 'menu-danger' : ''} onClick={() => { item.onSelect(); setOpen(false); triggerRef.current?.focus(); }}>{item.icon}{item.label}</button>)}</div>}</div>;
}
