// BetterWright CDP-free bridge — background service worker.
//
// Connects back to the BetterWright worker over a loopback WebSocket and
// executes narrowly scoped diagnostic reads through chrome.* extension APIs
// only. No DevTools protocol session attaches to the renderer; this makes the
// probe useful for comparing extension control with the regular runtime.
//
// RPC (JSON lines over WebSocket):
//   {id, op: "queryText", tabId?, selector}                           -> {value}
//   {id, op: "queryValue", tabId?, selector}                          -> {value}
//   {id, op: "navigate",  tabId?, url}                             -> {url}
//   {id, op: "tabs"}                                               -> {tabs[]}
//   {id, op: "newTab",    url?}                                    -> {tabId}
//   {id, op: "closeTab",  tabId}                                   -> {}
//   {id, op: "waitLoad",  tabId?, timeoutMs?}                      -> {status}
//
// The loopback port and bearer token arrive in config.js (generated per
// launch by the diagnostic script.

/* global BW_BRIDGE_CONFIG */

declare const BW_BRIDGE_CONFIG: { port?: number; token?: string };
declare const chrome: any;
declare function importScripts(...urls: string[]): void;

// Per-launch config (port + token), generated by the worker into this dir.
importScripts("config.js");

// config.js declares BW_BRIDGE_CONFIG as a script-level const, so when it is
// missing or corrupt the identifier is undeclared and evaluating it throws a
// ReferenceError; connect() then no-ops instead of the worker crashing.
function loadedBridgeConfig(): { port?: number; token?: string } | null {
  try {
    return BW_BRIDGE_CONFIG ?? null;
  } catch {
    return null;
  }
}

const config = loadedBridgeConfig();
const RETRY_MS = 2_000;

let socket = null;

function activeTabId() {
  return chrome.tabs
    .query({ active: true, currentWindow: true })
    .then((tabs) => tabs[0]?.id ?? null);
}

async function resolveTab(tabId) {
  const id = tabId ?? (await activeTabId());
  if (id == null) throw new Error("no active tab");
  return id;
}

const ops = {
  async queryText(request) {
    const tabId = await resolveTab(request.tabId);
    const [result] = await chrome.scripting.executeScript({
      target: { tabId, allFrames: false },
      func: (selector) => document.querySelector(selector)?.textContent ?? null,
      args: [String(request.selector ?? "")],
    });
    if (result?.error) throw new Error(String(result.error));
    return { value: result?.result ?? null };
  },

  async queryValue(request) {
    const tabId = await resolveTab(request.tabId);
    const [result] = await chrome.scripting.executeScript({
      target: { tabId, allFrames: false },
      func: (selector) => document.querySelector(selector)?.value ?? null,
      args: [String(request.selector ?? "")],
    });
    if (result?.error) throw new Error(String(result.error));
    return { value: result?.result ?? null };
  },

  async navigate(request) {
    const tabId = await resolveTab(request.tabId);
    await chrome.tabs.update(tabId, { url: String(request.url) });
    return ops.waitLoad({ tabId, timeoutMs: request.timeoutMs ?? 30_000 });
  },

  async tabs() {
    const tabs = await chrome.tabs.query({});
    return {
      tabs: tabs.map((tab) => ({
        id: tab.id,
        url: tab.url,
        title: tab.title,
        active: tab.active,
        windowId: tab.windowId,
      })),
    };
  },

  async newTab(request) {
    const tab = await chrome.tabs.create({ url: request.url || "about:blank" });
    return { tabId: tab.id };
  },

  async closeTab(request) {
    const tabId = await resolveTab(request.tabId);
    await chrome.tabs.remove(tabId);
    return {};
  },

  waitLoad(request) {
    const timeoutMs = request.timeoutMs ?? 30_000;
    return resolveTab(request.tabId).then(
      (tabId) =>
        new Promise((resolve, reject) => {
          const timer = setTimeout(() => {
            chrome.tabs.onUpdated.removeListener(listener);
            reject(new Error("waitLoad timed out"));
          }, timeoutMs);
          const listener = (updatedId, changeInfo) => {
            if (updatedId === tabId && changeInfo.status === "complete") {
              clearTimeout(timer);
              chrome.tabs.onUpdated.removeListener(listener);
              resolve({ status: "complete" });
            }
          };
          chrome.tabs.onUpdated.addListener(listener);
          chrome.tabs.get(tabId).then((tab) => {
            if (tab.status === "complete") {
              clearTimeout(timer);
              chrome.tabs.onUpdated.removeListener(listener);
              resolve({ status: "complete" });
            }
          });
        }),
    );
  },
};

function connect() {
  if (!config?.port || !config?.token) return;
  let ws;
  try {
    ws = new WebSocket(`ws://127.0.0.1:${config.port}/bridge`);
  } catch {
    setTimeout(connect, RETRY_MS);
    return;
  }
  socket = ws;
  ws.onopen = () => {
    ws.send(JSON.stringify({ hello: "bw-cdpfree-bridge", token: config.token }));
  };
  ws.onmessage = (event) => {
    let request;
    try {
      request = JSON.parse(event.data);
    } catch {
      return;
    }
    const op = ops[request?.op];
    if (!op) {
      ws.send(
        JSON.stringify({ id: request?.id, error: `unknown op: ${request?.op}` }),
      );
      return;
    }
    Promise.resolve()
      .then(() => op(request))
      .then((payload) => {
        ws.send(JSON.stringify({ id: request.id, ok: true, ...payload }));
      })
      .catch((error) => {
        ws.send(
          JSON.stringify({ id: request.id, error: String(error?.message || error) }),
        );
      });
  };
  ws.onclose = () => {
    socket = null;
    setTimeout(connect, RETRY_MS);
  };
  ws.onerror = () => {
    try {
      ws.close();
    } catch {
      /* reconnect handled by onclose */
    }
  };
}

connect();

// Reconnect after a transient socket close while the worker is alive.
setInterval(() => {
  if (!socket || socket.readyState !== WebSocket.OPEN) connect();
}, 20_000);
