import React, { useCallback, useMemo, useRef, useState } from 'react';
import { Animated, PanResponder, Platform, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import {
  apiAssignCounselingRequest, apiCreateAvailability, apiCreateBlockedPeriod, apiCreateCounselingNote,
  apiDeactivateAvailability, apiDeleteBlockedPeriod, apiGetAvailability, apiGetCounselingCalendar,
  apiGetCounselingRequests, apiGetCounselors, apiUpdateAppointment,
  type Appointment, type AvailabilityRule,
} from '@prototype/api-client';
import { errorMessage, useAdminResource } from '@/hooks/useAdminResource';
import { OperationalMetric, SectionHeader } from './OperationsUI';
import { SegmentedControl } from './ProductPrimitives';
import { MotionSurface, useReducedMotion } from './AdminMotion';
import { useAdminExperience } from './AdminExperience';
import { Badge, Button, Card, DataTable, Dialog, EmptyState, ErrorState, Field, FilterControl, LoadingState, Notice, Page, formatDate, ui } from '@/components/ui';
import { adminTheme as c } from '@/constants/adminTheme';

type WorkspaceView = 'week' | 'month' | 'list';
type WorkspaceTab = 'calendar' | 'requests' | 'availability';
type ChangeMode = 'move' | 'resize' | 'form';
type CreationKind = 'available' | 'blocked' | 'assign';
type CounselingRequestView = { id: string; student: string; nim: string; requestedAt: string; preference: string; status: 'waiting' | 'assigned' };
type CalendarEntryView = { id: string; date: string; start: string; end: string; counselorId: string; counselor: string; student?: string; nim?: string; faculty?: string; academicUnit?: string; requestId?: string; requestOrigin?: string; reason?: string; kind: 'appointment' | 'available' | 'blocked' | 'conflict'; status: string; history?: { id: string; type: string; at: string }[]; notes?: { id: string; text: string; at: string; author?: string | null }[] };
type Proposal = { original: CalendarEntryView; date: string; start: string; end: string; counselorId: string; mode: ChangeMode; problem?: string };
type RuleView = { id: string; counselorId: string; day: string; dayOfWeek: number; start: string; end: string; active: boolean; effectiveFrom?: string | null; effectiveTo?: string | null };

const DAY_START = 7 * 60, DAY_END = 19 * 60, HOUR_HEIGHT = 72;
const GRID_HEIGHT = ((DAY_END - DAY_START) / 60) * HOUR_HEIGHT;
const DAYS_ID = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
const DAYS_EN = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const ACTIVE = ['confirmed', 'rescheduled'];
const STATUSES = ['confirmed', 'completed', 'cancelled', 'rescheduled', 'no_show'];

const pad = (value: number) => String(value).padStart(2, '0');
const isoDate = (value: Date) => `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}`;
const parseDate = (value: string) => { const [year, month, day] = value.split('-').map(Number); return new Date(year, month - 1, day, 12); };
const addDays = (value: Date | string, amount: number) => { const next = typeof value === 'string' ? parseDate(value) : new Date(value); next.setDate(next.getDate() + amount); return next; };
const monday = (value: Date) => addDays(value, value.getDay() === 0 ? -6 : 1 - value.getDay());
const minutes = (value: string) => { const [hour, minute] = value.slice(0, 5).split(':').map(Number); return hour * 60 + minute; };
const clock = (value: number) => `${pad(Math.floor(Math.max(0, Math.min(value, 1439)) / 60))}:${pad(Math.max(0, Math.min(value, 1439)) % 60)}`;
const jakartaIso = (date: string, time: string) => `${date}T${time}:00+07:00`;
const overlap = (a: CalendarEntryView, start: string, end: string) => minutes(start) < minutes(a.end) && minutes(end) > minutes(a.start);
function jakartaPart(value: string, part: 'date' | 'time') {
  const options: Intl.DateTimeFormatOptions = part === 'date' ? { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' } : { timeZone: 'Asia/Jakarta', hour: '2-digit', minute: '2-digit', hour12: false };
  const parts = new Intl.DateTimeFormat('en-GB', options).formatToParts(new Date(value));
  const get = (type: string) => parts.find(item => item.type === type)?.value || '';
  return part === 'date' ? `${get('year')}-${get('month')}-${get('day')}` : `${get('hour')}:${get('minute')}`;
}
function visual(entry: CalendarEntryView) {
  if (entry.kind === 'available') return { color: c.success, background: c.successSoft, icon: 'event-available' as const, label: 'available', dashed: true };
  if (entry.kind === 'blocked') return { color: c.muted, background: c.surfaceInteractive, icon: 'block' as const, label: 'blocked', dashed: true };
  if (entry.kind === 'conflict') return { color: c.danger, background: c.dangerSoft, icon: 'report-problem' as const, label: 'conflict', dashed: true };
  if (entry.status === 'completed') return { color: c.success, background: c.successSoft, icon: 'check-circle' as const, label: 'completed', dashed: false };
  if (entry.status === 'cancelled') return { color: c.muted, background: c.surfaceMuted, icon: 'cancel' as const, label: 'cancelled', dashed: true };
  if (entry.status === 'rescheduled') return { color: c.lavender, background: c.lavenderSoft, icon: 'update' as const, label: 'rescheduled', dashed: false };
  if (entry.status === 'no_show') return { color: c.warning, background: c.warningSoft, icon: 'person-off' as const, label: 'no-show', dashed: true };
  return { color: c.blue, background: c.blueSoft, icon: 'event' as const, label: 'confirmed', dashed: false };
}

export default function CounselingWorkspace() {
  const params = useLocalSearchParams<{ counselor?: string }>();
  const { width } = useWindowDimensions();
  const { language } = useAdminExperience();
  const id = language === 'id', compact = width < 860, canDrag = Platform.OS === 'web' && width >= 1040;
  const today = isoDate(new Date());
  const [tab, setTab] = useState<WorkspaceTab>('calendar'), [view, setView] = useState<WorkspaceView>('week');
  const [offset, setOffset] = useState(0), [status, setStatus] = useState('');
  const [counselor, setCounselor] = useState(typeof params.counselor === 'string' ? params.counselor : '');
  const [from, setFrom] = useState(isoDate(monday(new Date()))), [to, setTo] = useState(isoDate(addDays(monday(new Date()), 6)));
  const [selected, setSelected] = useState<CalendarEntryView | null>(null), [proposal, setProposal] = useState<Proposal | null>(null), [request, setRequest] = useState<CounselingRequestView | null>(null);
  const [creation, setCreation] = useState(false), [creationKind, setCreationKind] = useState<CreationKind>('available'), [availabilityEditor, setAvailabilityEditor] = useState(false);
  const [date, setDate] = useState(today), [start, setStart] = useState('09:00'), [end, setEnd] = useState('10:00'), [reason, setReason] = useState(''), [requestId, setRequestId] = useState('');
  const [weekday, setWeekday] = useState(String(new Date().getDay())), [effectiveFrom, setEffectiveFrom] = useState(''), [effectiveTo, setEffectiveTo] = useState(''), [note, setNote] = useState('');
  const [busy, setBusy] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState(''), [monthDay, setMonthDay] = useState(today);
  const range = useMemo(() => {
    if (view === 'month') { const anchor = new Date(new Date().getFullYear(), new Date().getMonth() + offset, 1, 12); return { from: isoDate(anchor), to: isoDate(new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0, 12)), anchor }; }
    if (view === 'list') return { from, to, anchor: parseDate(from) };
    const anchor = addDays(monday(new Date()), offset * 7); return { from: isoDate(anchor), to: isoDate(addDays(anchor, 6)), anchor };
  }, [from, offset, to, view]);
  const calendarLoader = useCallback(() => apiGetCounselingCalendar(range.from, range.to, counselor || undefined, STATUSES.includes(status) ? status : undefined), [counselor, range.from, range.to, status]);
  const availabilityLoader = useCallback(() => apiGetAvailability(counselor || undefined), [counselor]);
  const calendarResource = useAdminResource(calendarLoader), requestResource = useAdminResource(apiGetCounselingRequests), counselorResource = useAdminResource(apiGetCounselors), availabilityResource = useAdminResource(availabilityLoader);
  const counselors = useMemo(() => (counselorResource.data?.counselors || []).filter(item => item.active).map(item => ({ id: item.user_id, name: item.nama })), [counselorResource.data]);
  const counselorOptions = useMemo(() => counselors.map(item => ({ value: item.id, label: item.name })), [counselors]);
  const counselorName = useCallback((value: string) => counselors.find(item => item.id === value)?.name || '—', [counselors]);
  const requests: CounselingRequestView[] = (requestResource.data?.requests || []).map(item => ({ id: item.counseling_request_id, student: item.nama, nim: item.nim || '—', requestedAt: item.created_at, preference: [item.faculty_name, item.academic_unit_name, item.preferred_context].filter(Boolean).join(' · ') || (id ? 'Tidak ditentukan' : 'Not specified'), status: item.status === 'requested' ? 'waiting' : 'assigned' }));
  const rules: RuleView[] = (availabilityResource.data?.availability || []).map((rule: AvailabilityRule) => ({ id: rule.availability_rule_id, counselorId: rule.counselor_id, day: (id ? DAYS_ID : DAYS_EN)[rule.day_of_week], dayOfWeek: rule.day_of_week, start: rule.start_time.slice(0, 5), end: rule.end_time.slice(0, 5), active: rule.active, effectiveFrom: rule.effective_from, effectiveTo: rule.effective_to }));

  const productionEntries = useMemo<CalendarEntryView[]>(() => {
    const appointments = (calendarResource.data?.appointments || []).map((item: Appointment): CalendarEntryView => ({ id: item.appointment_id, requestId: item.counseling_request_id || undefined, date: jakartaPart(item.starts_at, 'date'), start: jakartaPart(item.starts_at, 'time'), end: jakartaPart(item.ends_at, 'time'), counselorId: item.counselor_id, counselor: item.counselor_name || '—', student: item.student_name, nim: item.nim || undefined, faculty: item.faculty_name || undefined, academicUnit: item.academic_unit_name || undefined, requestOrigin: item.request_origin || undefined, kind: 'appointment', status: item.status, history: (item.history || []).map(event => ({ id: event.appointment_event_id, type: event.event_type, at: event.created_at })), notes: (item.admin_notes || []).map(itemNote => ({ id: itemNote.admin_note_id, text: itemNote.note_text, at: itemNote.created_at, author: itemNote.author_name })) }));
    const blocks = (calendarResource.data?.blocked_periods || []).map(item => ({ id: item.blocked_period_id, date: jakartaPart(item.starts_at, 'date'), start: jakartaPart(item.starts_at, 'time'), end: jakartaPart(item.ends_at, 'time'), counselorId: item.counselor_id, counselor: item.counselor_name, reason: item.reason || undefined, kind: 'blocked' as const, status: 'blocked' }));
    return [...appointments, ...blocks];
  }, [calendarResource.data]);
  const availabilityEntries = useMemo<CalendarEntryView[]>(() => {
    const dates: string[] = []; for (let cursor = parseDate(range.from); cursor <= parseDate(range.to); cursor = addDays(cursor, 1)) dates.push(isoDate(cursor));
    return rules.flatMap(rule => dates.filter(day => rule.active && parseDate(day).getDay() === rule.dayOfWeek && (!rule.effectiveFrom || day >= rule.effectiveFrom) && (!rule.effectiveTo || day <= rule.effectiveTo)).map(day => ({ id: `availability-${rule.id}-${day}`, date: day, start: rule.start, end: rule.end, counselorId: rule.counselorId, counselor: counselorName(rule.counselorId), kind: 'available' as const, status: 'available' })));
  }, [counselorName, range.from, range.to, rules]);
  const source = useMemo(() => [...productionEntries, ...availabilityEntries], [availabilityEntries, productionEntries]);
  const filtered = source.filter(item => (!counselor || item.counselorId === counselor) && (!status || item.status === status || item.kind === status));
  const weekDays = Array.from({ length: 7 }, (_, index) => isoDate(addDays(range.from, index)));
  const refresh = () => { calendarResource.reload(); requestResource.reload(); availabilityResource.reload(); };
  const fail = (caught: unknown) => { setError(errorMessage(caught)); setMessage(''); };

  const validate = useCallback((candidate: Omit<Proposal, 'problem'>) => {
    if (minutes(candidate.end) - minutes(candidate.start) < 30) return id ? 'Durasi minimum adalah 30 menit.' : 'Minimum duration is 30 minutes.';
    if (minutes(candidate.start) < DAY_START || minutes(candidate.end) > DAY_END) return id ? 'Waktu harus berada antara 07.00–19.00.' : 'Time must be between 07:00–19:00.';
    if (new Date(jakartaIso(candidate.date, candidate.start)).getTime() <= Date.now()) return id ? 'Janji temu tidak dapat dijadwalkan di masa lampau.' : 'Appointments cannot be scheduled in the past.';
    const hits = source.filter(item => item.id !== candidate.original.id && item.date === candidate.date && overlap(item, candidate.start, candidate.end));
    if (hits.some(item => item.kind === 'blocked' && item.counselorId === candidate.counselorId)) return id ? 'Waktu konselor sedang diblokir.' : 'The counselor is blocked at this time.';
    if (hits.some(item => item.kind === 'appointment' && ACTIVE.includes(item.status) && item.counselorId === candidate.counselorId)) return id ? 'Konselor sudah memiliki janji temu.' : 'The counselor already has an appointment.';
    if (candidate.original.student && hits.some(item => item.kind === 'appointment' && ACTIVE.includes(item.status) && item.student === candidate.original.student)) return id ? 'Mahasiswa sudah memiliki janji temu.' : 'The student already has an appointment.';
    const open = source.filter(item => item.kind === 'available' && item.counselorId === candidate.counselorId && item.date === candidate.date);
    if (open.length && !open.some(item => minutes(candidate.start) >= minutes(item.start) && minutes(candidate.end) <= minutes(item.end))) return id ? 'Waktu berada di luar ketersediaan konselor.' : 'Time is outside counselor availability.';
    return undefined;
  }, [id, source]);
  const makeProposal = (entry: CalendarEntryView, dayDelta: number, minuteDelta: number, mode: ChangeMode) => {
    const next: Proposal = { original: entry, date: mode === 'resize' ? entry.date : isoDate(addDays(entry.date, dayDelta)), start: mode === 'resize' ? entry.start : clock(minutes(entry.start) + minuteDelta), end: clock(minutes(entry.end) + minuteDelta), counselorId: entry.counselorId, mode };
    if (mode === 'resize') next.end = clock(minutes(entry.end) + minuteDelta); next.problem = validate(next); setProposal(next); setError('');
  };
  const editProposal = (changes: Partial<Proposal>) => setProposal(current => { if (!current) return null; const next = { ...current, ...changes }; return { ...next, problem: validate(next) }; });
  const persistProposal = async () => {
    if (!proposal || proposal.problem) return; setBusy('proposal'); setError('');
    try { await apiUpdateAppointment(proposal.original.id, { counselor_id: proposal.counselorId, starts_at: jakartaIso(proposal.date, proposal.start), ends_at: jakartaIso(proposal.date, proposal.end) }); calendarResource.reload(); setProposal(null); setMessage(id ? 'Perubahan jadwal berhasil disimpan.' : 'Schedule change saved.'); }
    catch (caught) { fail(caught); } finally { setBusy(''); }
  };
  const lifecycle = async (entry: CalendarEntryView, nextStatus: Appointment['status']) => {
    setBusy('lifecycle'); setError(''); try { await apiUpdateAppointment(entry.id, { status: nextStatus }); calendarResource.reload(); setSelected(current => current ? { ...current, status: nextStatus } : null); setMessage(id ? 'Status janji temu diperbarui.' : 'Appointment status updated.'); } catch (caught) { fail(caught); } finally { setBusy(''); }
  };
  const addNote = async () => {
    if (!selected || !note.trim()) return; setBusy('note'); setError('');
    try { await apiCreateCounselingNote({ appointment_id: selected.id, note_text: note.trim() }); calendarResource.reload(); setNote(''); setMessage(id ? 'Catatan internal ditambahkan.' : 'Internal note added.'); } catch (caught) { fail(caught); } finally { setBusy(''); }
  };
  const openCreation = (selectedDate = today, selectedStart = '09:00') => { setDate(selectedDate); setStart(selectedStart); setEnd(clock(minutes(selectedStart) + 60)); if (!counselor) setCounselor(counselors[0]?.id || ''); setReason(''); setCreation(true); setError(''); };
  const createItem = async () => {
    if (!counselor || minutes(end) <= minutes(start) || (creationKind === 'assign' && !requestId)) { setError(id ? 'Lengkapi semua bidang dengan nilai yang valid.' : 'Complete all fields with valid values.'); return; } setBusy('create'); setError('');
    try { if (creationKind === 'assign') await apiAssignCounselingRequest(requestId, { counselor_id: counselor, starts_at: jakartaIso(date, start), ends_at: jakartaIso(date, end) }); else if (creationKind === 'blocked') await apiCreateBlockedPeriod({ counselor_id: counselor, starts_at: jakartaIso(date, start), ends_at: jakartaIso(date, end), reason: reason || undefined }); else await apiCreateAvailability({ counselor_id: counselor, day_of_week: parseDate(date).getDay(), start_time: start, end_time: end, timezone: 'Asia/Jakarta', effective_from: date, effective_to: date, active: true }); setCreation(false); refresh(); setMessage(id ? 'Kalender berhasil diperbarui.' : 'Calendar updated.'); } catch (caught) { fail(caught); } finally { setBusy(''); }
  };
  const assign = async () => { if (!request || !counselor) return; setBusy('assign'); try { await apiAssignCounselingRequest(request.id, { counselor_id: counselor, starts_at: jakartaIso(date, start), ends_at: jakartaIso(date, end) }); setRequest(null); refresh(); setMessage(id ? 'Janji temu dikonfirmasi.' : 'Appointment confirmed.'); } catch (caught) { fail(caught); } finally { setBusy(''); } };
  const createRule = async () => { if (!counselor || minutes(end) <= minutes(start)) return; setBusy('rule'); try { await apiCreateAvailability({ counselor_id: counselor, day_of_week: Number(weekday), start_time: start, end_time: end, timezone: 'Asia/Jakarta', effective_from: effectiveFrom || null, effective_to: effectiveTo || null, active: true }); setAvailabilityEditor(false); availabilityResource.reload(); setMessage(id ? 'Ketersediaan berulang ditambahkan.' : 'Recurring availability added.'); } catch (caught) { fail(caught); } finally { setBusy(''); } };
  const deactivate = async (rule: RuleView) => { setBusy(rule.id); try { await apiDeactivateAvailability(rule.id); availabilityResource.reload(); } catch (caught) { fail(caught); } finally { setBusy(''); } };
  const removeBlock = async (entry: CalendarEntryView) => { setBusy('block'); try { await apiDeleteBlockedPeriod(entry.id); calendarResource.reload(); setSelected(null); } catch (caught) { fail(caught); } finally { setBusy(''); } };

  const statusOptions = [{ value: '', label: id ? 'Semua status' : 'All statuses' }, ...STATUSES.map(value => ({ value, label: value.replaceAll('_', ' ') })), { value: 'available', label: id ? 'Tersedia' : 'Available' }, { value: 'blocked', label: id ? 'Diblokir' : 'Blocked' }];
  return <Page title={id ? 'Ruang Kerja Konseling' : 'Counseling Workspace'} subtitle={id ? 'Kelola permintaan, kapasitas, konflik, dan siklus janji temu.' : 'Manage requests, capacity, conflicts, and appointment lifecycles.'} action={<Button label={id ? 'Buat jadwal' : 'Create schedule'} icon="add" onPress={() => openCreation()} />}>
    <View style={ui.grid}><OperationalMetric label={id ? 'Permintaan menunggu' : 'Waiting requests'} value={requests.filter(item => item.status === 'waiting').length} note={id ? 'Perlu penugasan' : 'Need assignment'} icon="pending-actions" tone="amber" /><OperationalMetric label={id ? 'Janji aktif' : 'Active appointments'} value={filtered.filter(item => item.kind === 'appointment' && ACTIVE.includes(item.status)).length} note={id ? 'Dalam periode aktif' : 'In active range'} icon="event" tone="blue" /><OperationalMetric label={id ? 'Kapasitas terbuka' : 'Open capacity'} value={filtered.filter(item => item.kind === 'available').length} note={id ? 'Blok ketersediaan' : 'Availability blocks'} icon="event-available" /><OperationalMetric label={id ? 'Waktu diblokir' : 'Blocked periods'} value={filtered.filter(item => item.kind === 'blocked').length} note={id ? 'Cuti, rapat, kegiatan' : 'Leave, meetings, activities'} icon="block" tone="red" /></View>
    {message && <MotionSurface><Notice>{message}</Notice></MotionSurface>}{error && <MotionSurface><ErrorState message={error} /></MotionSurface>}
    <View style={s.toolbar}><SegmentedControl value={tab} onChange={value => setTab(value as WorkspaceTab)} options={[{ value: 'calendar', label: id ? 'Kalender' : 'Calendar', icon: 'calendar-month' }, { value: 'requests', label: id ? 'Antrean' : 'Requests', icon: 'pending-actions' }, { value: 'availability', label: id ? 'Ketersediaan' : 'Availability', icon: 'schedule' }]} /><FilterControl label={id ? 'Konselor' : 'Counselor'} value={counselor} onChange={setCounselor} options={[{ value: '', label: id ? 'Semua konselor' : 'All counselors' }, ...counselorOptions]} /><Button label={id ? 'Muat ulang' : 'Refresh'} icon="refresh" tone="quiet" onPress={refresh} /></View>
    {tab === 'calendar' && <MotionSurface key={view}><View style={{ gap: 16 }}><View style={[ui.row, { justifyContent: 'space-between' }]}><SegmentedControl value={view} onChange={value => { setView(value as WorkspaceView); setOffset(0); }} options={[{ value: 'week', label: id ? 'Minggu' : 'Week' }, { value: 'month', label: id ? 'Bulan' : 'Month' }, { value: 'list', label: id ? 'Daftar' : 'List' }]} />{view !== 'list' && <View style={ui.row}><Button label="‹" tone="quiet" onPress={() => setOffset(value => value - 1)} /><Button label={id ? 'Hari ini' : 'Today'} tone="quiet" onPress={() => setOffset(0)} /><Button label="›" tone="quiet" onPress={() => setOffset(value => value + 1)} /><Text style={[ui.text, { fontWeight: '800' }]}>{view === 'month' ? range.anchor.toLocaleDateString(id ? 'id-ID' : 'en-US', { month: 'long', year: 'numeric' }) : `${formatDate(range.from)} – ${formatDate(range.to)}`}</Text></View>}</View><View style={s.filterBar}><FilterControl label="Status" value={status} onChange={setStatus} options={statusOptions} />{view === 'list' && <><Field label={id ? 'Dari tanggal' : 'Date from'} value={from} onChangeText={setFrom} /><Field label={id ? 'Sampai tanggal' : 'Date to'} value={to} onChangeText={setTo} /></>}</View>{!canDrag && view === 'week' && <Notice>{id ? 'Ketuk janji temu lalu gunakan Jadwalkan ulang. Drag dan resize tersedia pada desktop lebar.' : 'Tap an appointment and use Reschedule. Drag and resize are available on wide desktop screens.'}</Notice>}{calendarResource.loading ? <LoadingState /> : calendarResource.error ? <ErrorState message={calendarResource.error} retry={calendarResource.reload} /> : view === 'list' || compact ? <Card><ScheduleList entries={filtered} onSelect={setSelected} id={id} /></Card> : view === 'month' ? <><MonthCalendar anchor={range.anchor} entries={filtered} selectedDay={monthDay} onSelectDay={setMonthDay} onSelect={setSelected} id={id} /><DayAgenda date={monthDay} entries={filtered.filter(item => item.date === monthDay)} onSelect={setSelected} id={id} /></> : <WeekCalendar entries={filtered} days={weekDays} onSelect={setSelected} onDrop={makeProposal} onEmpty={openCreation} canDrag={canDrag} id={id} />}</View></MotionSurface>}
    {tab === 'requests' && <MotionSurface><Card><SectionHeader title={id ? 'Antrean permintaan konseling' : 'Counseling request queue'} description={id ? 'Tinjau metadata akademik, lalu tetapkan konselor serta waktu.' : 'Review academic metadata, then assign a counselor and time.'} /><DataTable rows={requests} rowKey={item => item.id} empty={id ? 'Tidak ada permintaan.' : 'No requests.'} columns={[{ title: id ? 'Mahasiswa' : 'Student', width: 220, render: item => <View><Text style={[ui.text, { fontWeight: '800' }]}>{item.student}</Text><Text style={ui.muted}>{item.nim}</Text></View> }, { title: id ? 'Diajukan' : 'Requested', width: 140, render: item => <Text style={ui.muted}>{formatDate(item.requestedAt)}</Text> }, { title: id ? 'Konteks akademik' : 'Academic context', width: 270, render: item => <Text style={ui.text}>{item.preference}</Text> }, { title: 'Status', width: 110, render: item => <Badge value={item.status} /> }, { title: id ? 'Tindakan' : 'Action', width: 135, render: item => <Button label={id ? 'Tugaskan' : 'Assign'} disabled={item.status !== 'waiting'} tone="quiet" onPress={() => { setRequest(item); setDate(today); setStart('09:00'); setEnd('10:00'); }} /> }]} /></Card></MotionSurface>}
    {tab === 'availability' && <MotionSurface><View style={ui.grid}><View style={[ui.column, { flexBasis: 600 }]}><Card><SectionHeader title={id ? 'Ketersediaan berulang' : 'Recurring availability'} description={id ? 'Aturan mingguan aktif untuk setiap konselor.' : 'Active weekly rules for each counselor.'} />{rules.length ? rules.map(rule => <View key={rule.id} style={s.row}><Text style={[ui.text, { width: 42, fontWeight: '900' }]}>{rule.day}</Text><Text style={[ui.text, { width: 105 }]}>{rule.start}–{rule.end}</Text><Text numberOfLines={1} style={[ui.muted, { flex: 1 }]}>{counselorName(rule.counselorId)}</Text><Badge value={rule.active ? 'active' : 'inactive'} />{rule.active && <Button label={id ? 'Nonaktifkan' : 'Deactivate'} disabled={busy === rule.id} tone="quiet" onPress={() => { void deactivate(rule); }} />}</View>) : <EmptyState message={id ? 'Belum ada aturan.' : 'No rules yet.'} />}<Button label={id ? 'Tambah aturan berulang' : 'Add recurring rule'} icon="add" onPress={() => setAvailabilityEditor(true)} /></Card></View><View style={[ui.column, { flexBasis: 340 }]}><Card title={id ? 'Waktu diblokir' : 'Blocked time'}><Text style={ui.muted}>{id ? 'Blokir cuti, rapat, ketidaktersediaan, atau kegiatan universitas.' : 'Block leave, meetings, unavailability, or university activities.'}</Text><Button label={id ? 'Buat waktu blokir' : 'Create blocked time'} icon="block" tone="quiet" onPress={() => { openCreation(); setCreationKind('blocked'); }} /></Card><Card title={id ? 'Validasi konflik' : 'Conflict validation'}><ConflictGuide id={id} /></Card></View></View></MotionSurface>}
    <DetailDialog selected={selected} id={id} busy={!!busy} note={note} setNote={setNote} onClose={() => setSelected(null)} onReschedule={entry => { const next: Proposal = { original: entry, date: entry.date, start: entry.start, end: entry.end, counselorId: entry.counselorId, mode: 'form' }; setProposal({ ...next, problem: validate(next) }); setSelected(null); }} onLifecycle={lifecycle} onAddNote={addNote} onDeleteBlock={removeBlock} />
    <Dialog title={id ? 'Ubah Jadwal Konseling?' : 'Change Counseling Schedule?'} visible={!!proposal} onClose={() => setProposal(null)} busy={busy === 'proposal'}>{proposal && <><View style={s.compare}><View style={{ flex: 1, gap: 4 }}><Text style={s.eyebrow}>{id ? 'SEBELUMNYA' : 'BEFORE'}</Text><Text style={ui.heading}>{formatDate(proposal.original.date)}</Text><Text style={ui.text}>{proposal.original.start}–{proposal.original.end} · {proposal.original.counselor}</Text></View><MaterialIcons name="arrow-forward" size={20} color={c.muted} /><View style={{ flex: 1, gap: 4 }}><Text style={s.eyebrow}>{id ? 'MENJADI' : 'AFTER'}</Text><Text style={ui.heading}>{formatDate(proposal.date)}</Text><Text style={ui.text}>{proposal.start}–{proposal.end} · {counselorName(proposal.counselorId)}</Text></View></View><Field label={id ? 'Tanggal' : 'Date'} value={proposal.date} onChangeText={value => editProposal({ date: value })} /><View style={ui.row}><Field label={id ? 'Mulai' : 'Start'} value={proposal.start} onChangeText={value => editProposal({ start: value })} /><Field label={id ? 'Selesai' : 'End'} value={proposal.end} onChangeText={value => editProposal({ end: value })} /></View><FilterControl label={id ? 'Konselor' : 'Counselor'} value={proposal.counselorId} onChange={value => editProposal({ counselorId: value })} options={counselorOptions} />{proposal.problem && <Notice danger>{proposal.problem}</Notice>}<Text style={ui.muted}>{id ? 'Backend memvalidasi konflik saat konfirmasi. Jika ditolak, jadwal lama tetap dipertahankan.' : 'The backend validates conflicts on confirmation. If rejected, the original schedule remains unchanged.'}</Text><View style={[ui.row, { justifyContent: 'flex-end' }]}><Button label={id ? 'Batal' : 'Cancel'} tone="quiet" onPress={() => setProposal(null)} /><Button label={busy === 'proposal' ? (id ? 'Memvalidasi…' : 'Validating…') : (id ? 'Konfirmasi Perubahan' : 'Confirm change')} disabled={!!proposal.problem || busy === 'proposal'} onPress={() => { void persistProposal(); }} /></View></>}</Dialog>
    <Dialog title={id ? 'Tinjau dan tugaskan' : 'Review and assign'} visible={!!request} onClose={() => setRequest(null)} busy={busy === 'assign'}>{request && <><Notice>{request.student} · {request.nim}<br />{request.preference}</Notice><FilterControl label={id ? 'Konselor' : 'Counselor'} value={counselor} onChange={setCounselor} options={counselorOptions} /><Field label={id ? 'Tanggal' : 'Date'} value={date} onChangeText={setDate} /><View style={ui.row}><Field label={id ? 'Mulai' : 'Start'} value={start} onChangeText={setStart} /><Field label={id ? 'Selesai' : 'End'} value={end} onChangeText={setEnd} /></View><Button label={id ? 'Konfirmasi janji temu' : 'Confirm appointment'} disabled={!counselor || busy === 'assign'} onPress={() => { void assign(); }} /></>}</Dialog>
    <Dialog title={id ? 'Buat dari kalender' : 'Create from calendar'} visible={creation} onClose={() => setCreation(false)} busy={busy === 'create'}><SegmentedControl value={creationKind} onChange={value => setCreationKind(value as CreationKind)} options={[{ value: 'available', label: id ? 'Slot tersedia' : 'Available slot', icon: 'event-available' }, { value: 'blocked', label: id ? 'Waktu blokir' : 'Blocked time', icon: 'block' }, { value: 'assign', label: id ? 'Tugaskan permintaan' : 'Assign request', icon: 'pending-actions' }]} /><FilterControl label={id ? 'Konselor' : 'Counselor'} value={counselor} onChange={setCounselor} options={counselorOptions} /><Field label={id ? 'Tanggal' : 'Date'} value={date} onChangeText={setDate} /><View style={ui.row}><Field label={id ? 'Mulai' : 'Start'} value={start} onChangeText={setStart} /><Field label={id ? 'Selesai' : 'End'} value={end} onChangeText={setEnd} /></View>{creationKind === 'blocked' && <Field label={id ? 'Alasan' : 'Reason'} value={reason} onChangeText={setReason} placeholder={id ? 'Cuti, rapat, kegiatan universitas…' : 'Leave, meeting, university activity…'} />}{creationKind === 'assign' && <FilterControl label={id ? 'Permintaan menunggu' : 'Waiting request'} value={requestId} onChange={setRequestId} options={requests.filter(item => item.status === 'waiting').map(item => ({ value: item.id, label: `${item.student} · ${item.nim}` }))} />}<Button label={id ? 'Simpan' : 'Save'} disabled={busy === 'create'} onPress={() => { void createItem(); }} /></Dialog>
    <Dialog title={id ? 'Tambah ketersediaan berulang' : 'Add recurring availability'} visible={availabilityEditor} onClose={() => setAvailabilityEditor(false)} busy={busy === 'rule'}><FilterControl label={id ? 'Konselor' : 'Counselor'} value={counselor} onChange={setCounselor} options={counselorOptions} /><FilterControl label={id ? 'Hari' : 'Weekday'} value={weekday} onChange={setWeekday} options={(id ? DAYS_ID : DAYS_EN).map((label, index) => ({ value: String(index), label }))} /><View style={ui.row}><Field label={id ? 'Mulai' : 'Start'} value={start} onChangeText={setStart} /><Field label={id ? 'Selesai' : 'End'} value={end} onChangeText={setEnd} /></View><View style={ui.row}><Field label={id ? 'Berlaku mulai (opsional)' : 'Effective from (optional)'} value={effectiveFrom} onChangeText={setEffectiveFrom} /><Field label={id ? 'Berlaku sampai (opsional)' : 'Effective to (optional)'} value={effectiveTo} onChangeText={setEffectiveTo} /></View><Button label={id ? 'Tambah aturan' : 'Add rule'} disabled={busy === 'rule'} onPress={() => { void createRule(); }} /></Dialog>
  </Page>;
}

function DetailDialog({ selected, id, busy, note, setNote, onClose, onReschedule, onLifecycle, onAddNote, onDeleteBlock }: { selected: CalendarEntryView | null; id: boolean; busy: boolean; note: string; setNote: (value: string) => void; onClose: () => void; onReschedule: (entry: CalendarEntryView) => void; onLifecycle: (entry: CalendarEntryView, status: Appointment['status']) => Promise<void>; onAddNote: () => Promise<void>; onDeleteBlock: (entry: CalendarEntryView) => Promise<void> }) {
  const style = selected ? visual(selected) : null, active = selected?.kind === 'appointment' && ACTIVE.includes(selected.status);
  return <Dialog title={selected?.kind === 'blocked' ? (id ? 'Detail waktu blokir' : 'Blocked-time details') : (id ? 'Detail janji temu' : 'Appointment details')} visible={!!selected} onClose={onClose} busy={busy}>
    {selected && style && <>
      <View style={[s.hero, { backgroundColor: style.background, borderColor: style.color, borderStyle: style.dashed ? 'dashed' : 'solid' }]}>
        <View style={ui.row}><MaterialIcons name={style.icon} color={style.color} size={21} /><Badge value={selected.status} /></View>
        <Text style={ui.heading}>{formatDate(selected.date)} · {selected.start}–{selected.end}</Text><Text style={ui.text}>{selected.counselor}</Text>
        {selected.kind === 'blocked' ? <Text style={ui.muted}>{selected.reason || '—'}</Text> : <><Text style={[ui.text, { fontWeight: '800' }]}>{selected.student || '—'} · {selected.nim || '—'}</Text><Text style={ui.muted}>{[selected.faculty, selected.academicUnit].filter(Boolean).join(' · ') || (id ? 'Metadata akademik belum tersedia' : 'Academic metadata unavailable')}</Text><Text style={ui.muted}>{id ? 'Asal permintaan' : 'Request origin'}: {selected.requestOrigin || '—'}</Text></>}
      </View>
      {selected.kind === 'blocked' && <Button label={id ? 'Hapus waktu blokir' : 'Remove blocked time'} tone="danger" disabled={busy} onPress={() => { void onDeleteBlock(selected); }} />}
      {selected.kind === 'appointment' && <>
        {active && <View style={ui.row}><Button label={id ? 'Jadwalkan ulang' : 'Reschedule'} tone="quiet" onPress={() => onReschedule(selected)} /><Button label={id ? 'Selesai' : 'Complete'} tone="quiet" disabled={busy} onPress={() => { void onLifecycle(selected, 'completed'); }} /><Button label="No-show" tone="quiet" disabled={busy} onPress={() => { void onLifecycle(selected, 'no_show'); }} /><Button label={id ? 'Batalkan' : 'Cancel'} tone="danger" disabled={busy} onPress={() => { void onLifecycle(selected, 'cancelled'); }} /></View>}
        <View style={s.section}><Text style={ui.heading}>{id ? 'Riwayat janji temu' : 'Appointment history'}</Text>{selected.history?.length ? selected.history.map(item => <View key={item.id} style={s.timeline}><MaterialIcons name="history" size={16} color={c.primary} /><View><Text style={[ui.text, { fontWeight: '700' }]}>{item.type.replaceAll('_', ' ')}</Text><Text style={ui.muted}>{formatDate(item.at)}</Text></View></View>) : <Text style={ui.muted}>{id ? 'Belum ada riwayat.' : 'No recorded history yet.'}</Text>}</View>
        <View style={s.section}><Text style={ui.heading}>{id ? 'Catatan internal' : 'Internal notes'}</Text>{selected.notes?.map(item => <View key={item.id} style={s.note}><Text style={ui.text}>{item.text}</Text><Text style={ui.muted}>{item.author || 'Admin'} · {formatDate(item.at)}</Text></View>)}<Field label={id ? 'Catatan baru' : 'New note'} value={note} onChangeText={setNote} multiline /><Button label={id ? 'Tambah catatan' : 'Add note'} disabled={!note.trim() || busy} tone="quiet" onPress={() => { void onAddNote(); }} /></View>
      </>}
    </>}
  </Dialog>;
}

function ScheduleList({ entries, onSelect, id }: { entries: CalendarEntryView[]; onSelect: (entry: CalendarEntryView) => void; id: boolean }) {
  return <DataTable rows={entries} rowKey={item => item.id} empty={id ? 'Tidak ada jadwal.' : 'No schedules.'} columns={[{ title: id ? 'Tanggal' : 'Date', width: 135, render: item => <Text style={[ui.text, { fontWeight: '800' }]}>{formatDate(item.date)}</Text> }, { title: id ? 'Waktu' : 'Time', width: 110, render: item => <Text style={ui.text}>{item.start}–{item.end}</Text> }, { title: id ? 'Mahasiswa / agenda' : 'Student / event', width: 220, render: item => <Text style={ui.text}>{item.student || item.reason || (item.kind === 'available' ? (id ? 'Kapasitas terbuka' : 'Open capacity') : '—')}</Text> }, { title: id ? 'Konselor' : 'Counselor', width: 190, render: item => <Text style={ui.text}>{item.counselor}</Text> }, { title: 'Status', width: 125, render: item => <Badge value={item.status} /> }, { title: id ? 'Tindakan' : 'Action', width: 100, render: item => <Button label={id ? 'Detail' : 'Details'} tone="quiet" onPress={() => onSelect(item)} /> }]} />;
}

function WeekCalendar({ entries, days, onSelect, onDrop, onEmpty, canDrag, id }: { entries: CalendarEntryView[]; days: string[]; onSelect: (entry: CalendarEntryView) => void; onDrop: (entry: CalendarEntryView, dayDelta: number, minuteDelta: number, mode: ChangeMode) => void; onEmpty: (date: string, start: string) => void; canDrag: boolean; id: boolean }) {
  const [gridWidth, setGridWidth] = useState(1120), today = isoDate(new Date()), now = new Date(), nowMinutes = now.getHours() * 60 + now.getMinutes(); const dayWidth = Math.max(126, (gridWidth - 72) / 7); const slots = Array.from({ length: (DAY_END - DAY_START) / 30 }, (_, index) => DAY_START + index * 30);
  return <View style={s.calendar}><ScrollView horizontal contentContainerStyle={{ minWidth: 1120 }}><View style={{ flex: 1 }} onLayout={event => setGridWidth(event.nativeEvent.layout.width)}><View style={s.weekHeader}><View style={s.timeHeader}><Text style={ui.muted}>WIB</Text></View>{days.map(day => <View key={day} style={[s.dayHeader, day === today && s.today]}><Text style={[ui.muted, { fontWeight: '800' }]}>{parseDate(day).toLocaleDateString(id ? 'id-ID' : 'en-US', { weekday: 'short' })}</Text><Text style={[ui.text, { fontWeight: '900', color: day === today ? c.primary : c.text }]}>{parseDate(day).getDate()}</Text></View>)}</View><View style={{ flexDirection: 'row', height: GRID_HEIGHT }}><View style={s.axis}>{Array.from({ length: 13 }, (_, index) => DAY_START + index * 60).map(time => <Text key={time} style={[ui.muted, { position: 'absolute', top: ((time - DAY_START) / 60) * HOUR_HEIGHT - 7, right: 10 }]}>{clock(time)}</Text>)}</View>{days.map(day => <View key={day} style={[s.dayColumn, day === today && { backgroundColor: c.primarySoft }]}>{slots.map(slot => <Pressable key={slot} accessibilityRole="button" accessibilityLabel={`${formatDate(day)} ${clock(slot)}`} onPress={() => onEmpty(day, clock(slot))} style={{ height: HOUR_HEIGHT / 2, borderTopWidth: slot % 60 === 0 ? 1 : StyleSheet.hairlineWidth, borderColor: c.border }} />)}{entries.filter(item => item.date === day).map(entry => <CalendarBlock key={entry.id} entry={entry} dayWidth={dayWidth} canDrag={canDrag} onPress={() => onSelect(entry)} onDrop={(dayDelta, minuteDelta, mode) => onDrop(entry, dayDelta, minuteDelta, mode)} />)}{day === today && nowMinutes >= DAY_START && nowMinutes <= DAY_END && <View pointerEvents="none" style={[s.now, { top: ((nowMinutes - DAY_START) / 60) * HOUR_HEIGHT }]}><View style={s.nowDot} /><Text style={s.nowText}>{id ? 'sekarang' : 'now'}</Text></View>}</View>)}</View></View></ScrollView><View style={s.legend}>{['available', 'confirmed', 'completed', 'cancelled', 'rescheduled', 'no_show', 'blocked'].map(value => { const item = visual({ kind: value === 'available' || value === 'blocked' ? value : 'appointment', status: value } as CalendarEntryView); return <View key={value} style={[ui.row, { gap: 4 }]}><MaterialIcons name={item.icon} size={14} color={item.color} /><Text style={ui.muted}>{value.replaceAll('_', ' ')}</Text></View>; })}</View></View>;
}

function CalendarBlock({ entry, dayWidth, canDrag, onPress, onDrop }: { entry: CalendarEntryView; dayWidth: number; canDrag: boolean; onPress: () => void; onDrop: (dayDelta: number, minuteDelta: number, mode: ChangeMode) => void }) {
  const reduced = useReducedMotion(), move = useRef(new Animated.ValueXY()).current, resize = useRef(new Animated.Value(0)).current; const [dragging, setDragging] = useState(false), style = visual(entry), draggable = canDrag && entry.kind === 'appointment' && ACTIVE.includes(entry.status);
  const movePan = useMemo(() => PanResponder.create({ onStartShouldSetPanResponder: () => draggable, onMoveShouldSetPanResponder: (_, gesture) => draggable && Math.abs(gesture.dx) + Math.abs(gesture.dy) > 5, onPanResponderGrant: () => { setDragging(true); move.setValue({ x: 0, y: 0 }); }, onPanResponderMove: (_, gesture) => move.setValue({ x: gesture.dx, y: gesture.dy }), onPanResponderRelease: (_, gesture) => { setDragging(false); move.setValue({ x: 0, y: 0 }); const dayDelta = Math.round(gesture.dx / dayWidth), minuteDelta = Math.round(gesture.dy / (HOUR_HEIGHT / 4)) * 15; if (dayDelta || minuteDelta) onDrop(dayDelta, minuteDelta, 'move'); }, onPanResponderTerminate: () => { setDragging(false); move.setValue({ x: 0, y: 0 }); } }), [dayWidth, draggable, move, onDrop]);
  const resizePan = useMemo(() => PanResponder.create({ onStartShouldSetPanResponder: () => draggable, onMoveShouldSetPanResponder: () => draggable, onPanResponderGrant: () => { setDragging(true); resize.setValue(0); }, onPanResponderMove: (_, gesture) => resize.setValue(gesture.dy), onPanResponderRelease: (_, gesture) => { setDragging(false); resize.setValue(0); const delta = Math.round(gesture.dy / (HOUR_HEIGHT / 4)) * 15; if (delta) onDrop(0, delta, 'resize'); }, onPanResponderTerminate: () => { setDragging(false); resize.setValue(0); } }), [draggable, onDrop, resize]);
  const top = ((minutes(entry.start) - DAY_START) / 60) * HOUR_HEIGHT, height = Math.max(30, ((minutes(entry.end) - minutes(entry.start)) / 60) * HOUR_HEIGHT);
  return <>{dragging && <View pointerEvents="none" style={[s.event, { top, height, backgroundColor: style.background, borderColor: style.color, opacity: .25 }]} />}<Animated.View {...movePan.panHandlers} style={[s.event, { top, height, backgroundColor: style.background, borderColor: style.color, borderStyle: style.dashed ? 'dashed' : 'solid', zIndex: dragging ? 20 : 3, opacity: dragging ? .92 : 1, transform: draggable && !reduced ? move.getTranslateTransform() : undefined, shadowOpacity: dragging ? .22 : 0 }]}><Pressable accessibilityRole="button" accessibilityLabel={`${entry.student || entry.reason || entry.counselor}, ${entry.start}–${entry.end}, ${style.label}`} onPress={onPress} style={{ flex: 1, padding: 6, gap: 2 }}><View style={[ui.row, { gap: 4, flexWrap: 'nowrap' }]}><MaterialIcons name={style.icon} size={13} color={style.color} /><Text numberOfLines={1} style={{ color: style.color, fontSize: 9, fontWeight: '900', textTransform: 'uppercase' }}>{entry.start} · {style.label}</Text></View><Text numberOfLines={1} style={{ color: c.text, fontSize: 10, fontWeight: '700' }}>{entry.student || entry.reason || entry.counselor}</Text>{height > 52 && <Text numberOfLines={1} style={{ color: c.muted, fontSize: 9 }}>{entry.counselor}</Text>}</Pressable>{draggable && <Animated.View accessibilityLabel="Resize appointment duration" {...resizePan.panHandlers} style={[s.resize, !reduced && { transform: [{ translateY: resize }] }]}><View style={s.grip} /></Animated.View>}</Animated.View></>;
}

function MonthCalendar({ anchor, entries, selectedDay, onSelectDay, onSelect, id }: { anchor: Date; entries: CalendarEntryView[]; selectedDay: string; onSelectDay: (value: string) => void; onSelect: (entry: CalendarEntryView) => void; id: boolean }) {
  const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1, 12), gridStart = addDays(first, -(first.getDay() === 0 ? 6 : first.getDay() - 1)), days = Array.from({ length: 42 }, (_, index) => isoDate(addDays(gridStart, index))), today = isoDate(new Date());
  return <View style={s.month}><View style={s.weekdays}>{(id ? ['Sen','Sel','Rab','Kam','Jum','Sab','Min'] : ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']).map(day => <Text key={day} style={[ui.muted, { width: '14.2857%', textAlign: 'center', fontWeight: '800' }]}>{day}</Text>)}</View><View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>{days.map(day => { const rows = entries.filter(item => item.date === day), outside = parseDate(day).getMonth() !== anchor.getMonth(); return <Pressable key={day} accessibilityRole="button" accessibilityLabel={`${formatDate(day)}, ${rows.length} events`} onPress={() => onSelectDay(day)} style={[s.monthCell, selectedDay === day && { borderColor: c.primary, borderWidth: 2 }, day === today && { backgroundColor: c.primarySoft }, outside && { opacity: .45 }]}><Text style={[ui.text, { fontWeight: '800' }]}>{parseDate(day).getDate()}</Text><View style={{ flexDirection: 'row', gap: 3, flexWrap: 'wrap' }}>{rows.slice(0, 6).map(item => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`${item.start} ${visual(item).label}`} onPress={() => onSelect(item)} style={{ width: 8, height: 8, borderRadius: item.kind === 'blocked' ? 1 : 4, backgroundColor: visual(item).color }} />)}</View><Text style={ui.muted}>{rows.length ? `${rows.length} ${id ? 'agenda' : 'events'}` : '—'}</Text></Pressable>; })}</View></View>;
}
function DayAgenda({ date, entries, onSelect, id }: { date: string; entries: CalendarEntryView[]; onSelect: (entry: CalendarEntryView) => void; id: boolean }) { return <Card title={`Agenda · ${formatDate(date)}`}>{entries.length ? [...entries].sort((a, b) => a.start.localeCompare(b.start)).map(entry => <Pressable key={entry.id} accessibilityRole="button" onPress={() => onSelect(entry)} style={s.row}><MaterialIcons name={visual(entry).icon} size={18} color={visual(entry).color} /><Text style={[ui.text, { width: 100, fontWeight: '800' }]}>{entry.start}–{entry.end}</Text><Text style={[ui.text, { flex: 1 }]}>{entry.student || entry.reason || entry.counselor}</Text><Badge value={entry.status} /></Pressable>) : <EmptyState message={id ? 'Tidak ada agenda pada tanggal ini.' : 'No events on this date.'} />}</Card>; }
function ConflictGuide({ id }: { id: boolean }) { const items = id ? ['Konselor sudah memiliki janji temu', 'Mahasiswa memiliki jadwal lain', 'Waktu diblokir atau di luar ketersediaan', 'Tanggal atau waktu sudah lewat', 'Durasi minimum 30 menit'] : ['Counselor is already booked', 'Student has another appointment', 'Time is blocked or outside availability', 'Date or time is in the past', 'Minimum duration is 30 minutes']; return <View style={{ gap: 9 }}>{items.map(item => <View key={item} style={[ui.row, { flexWrap: 'nowrap' }]}><MaterialIcons name="report-problem" color={c.warning} size={17} /><Text style={[ui.muted, { flex: 1 }]}>{item}</Text></View>)}</View>; }

const s = StyleSheet.create({
  toolbar: { backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 14, gap: 14, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', justifyContent: 'space-between' }, filterBar: { backgroundColor: c.surfaceMuted, borderWidth: 1, borderColor: c.border, borderRadius: 12, padding: 12, gap: 12, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end' },
  calendar: { borderWidth: 1, borderColor: c.border, borderRadius: 16, overflow: 'hidden', backgroundColor: c.surface }, weekHeader: { flexDirection: 'row', backgroundColor: c.surfaceMuted, borderBottomWidth: 1, borderColor: c.border }, timeHeader: { width: 72, padding: 12 }, dayHeader: { flex: 1, minWidth: 126, padding: 10, borderLeftWidth: 1, borderColor: c.border, alignItems: 'center', gap: 2 }, today: { backgroundColor: c.primarySoft, borderTopWidth: 3, borderTopColor: c.primary }, axis: { width: 72, borderRightWidth: 1, borderColor: c.border, position: 'relative' }, dayColumn: { flex: 1, minWidth: 126, borderRightWidth: 1, borderColor: c.border, position: 'relative' },
  event: { position: 'absolute', left: 5, right: 5, borderLeftWidth: 4, borderWidth: 1, borderRadius: 8, overflow: 'visible', shadowColor: c.text, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } }, resize: { position: 'absolute', left: 0, right: 0, bottom: -7, height: 16, alignItems: 'center', justifyContent: 'center' }, grip: { width: 30, height: 4, borderRadius: 2, backgroundColor: c.borderStrong }, now: { position: 'absolute', left: 0, right: 0, height: 2, backgroundColor: c.danger, zIndex: 30 }, nowDot: { position: 'absolute', left: -4, top: -3, width: 8, height: 8, borderRadius: 4, backgroundColor: c.danger }, nowText: { position: 'absolute', right: 4, top: -14, color: c.danger, fontSize: 8, fontWeight: '900' }, legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, padding: 12, borderTopWidth: 1, borderColor: c.border },
  month: { backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, overflow: 'hidden' }, weekdays: { flexDirection: 'row', backgroundColor: c.surfaceMuted, paddingVertical: 10 }, monthCell: { width: '14.2857%', minHeight: 94, padding: 8, borderRightWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: c.border, gap: 8 }, row: { minHeight: 58, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10, paddingVertical: 10, paddingHorizontal: 8, borderBottomWidth: 1, borderColor: c.border },
  compare: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, alignItems: 'center', backgroundColor: c.surfaceMuted, borderRadius: 12, padding: 14 }, eyebrow: { color: c.muted, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 }, hero: { borderWidth: 1, borderLeftWidth: 4, borderRadius: 12, padding: 14, gap: 6 }, section: { borderTopWidth: 1, borderColor: c.border, paddingTop: 14, gap: 10 }, timeline: { flexDirection: 'row', gap: 9, alignItems: 'center' }, note: { backgroundColor: c.surfaceMuted, borderRadius: 10, padding: 11, gap: 4 },
});
