import { apiRequest } from '@/lib/api/client';
import type { DirectoryResponse, InstrumentDefinitionDraft, InstrumentDetail, LocalInstrumentDraft, QuestionDraft, ValidationResponse } from './types';

export const getInstruments = (signal?: AbortSignal) => apiRequest<DirectoryResponse>('/admin/assessment-instruments', { signal });
export const getInstrumentVersion = (versionId: string, signal?: AbortSignal) => apiRequest<InstrumentDetail>(`/admin/assessment-instruments/versions/${encodeURIComponent(versionId)}`, { signal });
export const createInstrumentDraft = (instrumentId: string) => apiRequest<InstrumentDetail>(`/admin/assessment-instruments/${encodeURIComponent(instrumentId)}/drafts`, { method: 'POST' });
export const saveInstrumentDraft = (versionId: string, questions: QuestionDraft[], expectedRevision?: number, definition?: InstrumentDefinitionDraft) => apiRequest<InstrumentDetail>(`/admin/assessment-instruments/versions/${encodeURIComponent(versionId)}/draft`, { method: 'PUT', body: { expected_revision: expectedRevision, questions: questions.map(({ item_key, category, position, wording, active, options }) => ({ item_key, category, position, wording, active, options: options.map(({ position: optionPosition, label, score }) => ({ position: optionPosition, label, score })) })), ...(definition ? { definition } : {}) } });
export const validateInstrument = (versionId: string) => apiRequest<ValidationResponse>(`/admin/assessment-instruments/versions/${encodeURIComponent(versionId)}/validate`, { method: 'POST' });
export const createCustomInstrument = (draft: LocalInstrumentDraft) => apiRequest<{instrument_id:string;instrument_version_id:string;definition_revision:number;status:string}>('/admin/assessment-instruments', { method:'POST', body:{code:draft.code,name:draft.name,description:draft.description,language:draft.language,dimensions:draft.dimensions.map((code,position)=>({code,name:code,position:position+1,multiplier:1,interpretation_bands:[]})),questions:draft.questions.map(({item_key,category,position,wording,active,options})=>({item_key,dimension_code:category,position,wording,active,options})),scoring:{strategy:'sum_by_dimension'}} });
export const submitInstrumentReview = (versionId:string, revision:number) => apiRequest<{review:unknown}>(`/admin/assessment-instruments/versions/${encodeURIComponent(versionId)}/submit-review?expected_revision=${revision}`, {method:'POST'});
export const publishInstrument = (versionId:string) => apiRequest<InstrumentDetail>(`/admin/assessment-instruments/versions/${encodeURIComponent(versionId)}/publish`, {method:'POST'});
