'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useLanguage } from '@/components/providers/LanguageProvider';
import { Badge, Button, EmptyState, ErrorState, PageShell, Skeleton } from '@/components/ui';
import { getInstruments, getInstrumentVersion } from './api';
import { filterDirectory, latestVersion, normalizeDirectory, statusTone } from './model';
import type { DirectoryItem, InstrumentDetail, InstrumentStatus } from './types';

export function InstrumentDirectory(){
 const {language,text}=useLanguage();const copy=text.instruments;const [rows,setRows]=useState<DirectoryItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [refresh,setRefresh]=useState(0);const [search,setSearch]=useState('');const [kind,setKind]=useState<'all'|'standard'|'custom'>('all');const [status,setStatus]=useState<'all'|InstrumentStatus>('all');
 useEffect(()=>{const controller=new AbortController();getInstruments(controller.signal).then(async(result)=>{const versions=result.instruments.map(latestVersion).filter(Boolean);const settled=await Promise.allSettled(versions.map((version)=>getInstrumentVersion(version!.instrument_version_id,controller.signal)));const details=new Map<string,InstrumentDetail>();settled.forEach((entry,index)=>{if(entry.status==='fulfilled')details.set(versions[index]!.instrument_version_id,entry.value)});setRows(normalizeDirectory(result.instruments,details));setError(false);setLoading(false)}).catch((caught)=>{if(!(caught instanceof DOMException&&caught.name==='AbortError')){setError(true);setLoading(false)}});return()=>controller.abort()},[refresh]);
 const filtered=useMemo(()=>filterDirectory(rows,search,kind,status),[rows,search,kind,status]);
 return <PageShell title={copy.title} actions={<><Button variant="secondary" icon="refresh" onClick={()=>setRefresh((x)=>x+1)}>{copy.refresh}</Button><Link className="button button-primary" href="/instruments/new">+ {copy.create}</Link></>} filters={<div className="instrument-filters" aria-label={copy.title}><label><span className="sr-only">{copy.search}</span><input type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder={copy.search}/></label><label><span className="sr-only">{copy.fields.type}</span><select value={kind} onChange={(e)=>setKind(e.target.value as typeof kind)}><option value="all">{copy.allTypes}</option><option value="standard">{copy.type.standard}</option><option value="custom">{copy.type.custom}</option></select></label><label><span className="sr-only">{copy.fields.status}</span><select value={status} onChange={(e)=>setStatus(e.target.value as typeof status)}><option value="all">{copy.allStatuses}</option><option value="draft">{copy.status.draft}</option><option value="published">{copy.status.published}</option><option value="archived">{copy.status.archived}</option></select></label></div>}>
  <p className="page-lead">{copy.subtitle}</p>
  {loading?<section className="instrument-card"><Skeleton lines={7}/></section>:error?<ErrorState title={copy.errors.title} message={copy.errors.load} retry={()=>setRefresh((x)=>x+1)} retryLabel={text.common.retry}/>:rows.length===0?<EmptyState title={copy.empty.title} message={copy.empty.body} action={<Link className="button button-primary" href="/instruments/new">+ {copy.create}</Link>}/>:<div className="table-shell instrument-table"><table><thead><tr><th>{copy.fields.name}</th><th>{copy.fields.type}</th><th>{copy.fields.version}</th><th>{copy.fields.status}</th><th>{copy.fields.questions}</th><th>{copy.fields.dimensions}</th><th>{copy.fields.updated}</th><th>{copy.fields.validation}</th><th>{copy.fields.action}</th></tr></thead><tbody>{filtered.map(({instrument,version,questionCount,categories})=><tr key={instrument.instrument_id}><td><strong>{instrument.name}</strong><small>{instrument.code}</small></td><td><Badge tone={instrument.instrument_kind==='standard'?'info':'neutral'}>{copy.type[instrument.instrument_kind]}</Badge></td><td>{version?`v${version.version_number}`:'—'}</td><td>{version?<Badge tone={statusTone(version.status)}>{copy.status[version.status]}</Badge>:'—'}</td><td>{questionCount??copy.questionCountUnknown}</td><td>{categories.length?categories.map((x)=>copy.dimensions[x]).join(', '):copy.dimensionsUnknown}</td><td>{version?formatDate(version.updated_at,language):'—'}</td><td><Badge tone="warning">{copy.validation.notSubmitted}</Badge></td><td><Link className="button button-secondary" href={`/instruments/${instrument.instrument_id}`}>{copy.actions.open}</Link></td></tr>)}</tbody></table>{filtered.length===0&&<EmptyState title={copy.empty.title}/>}</div>}
 </PageShell>
}
function formatDate(value:string,language:'id'|'en'){return new Intl.DateTimeFormat(language==='id'?'id-ID':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
