import type { Category, DirectoryItem, Instrument, InstrumentDetail, InstrumentStatus, LocalInstrumentDraft, QuestionDraft } from './types';

export const CATEGORIES: Category[] = ['depression', 'anxiety', 'stress'];
export function latestVersion(instrument: Instrument) { return [...instrument.versions].sort((a,b)=>b.version_number-a.version_number)[0] ?? null; }
export function normalizeDirectory(instruments: Instrument[], details: Map<string, InstrumentDetail>): DirectoryItem[] { return instruments.map((instrument)=>{const version=latestVersion(instrument);const detail=version?details.get(version.instrument_version_id):undefined;return{instrument,version,questionCount:detail?.questions.filter((q)=>q.active).length??null,categories:detail?[...new Set(detail.questions.filter((q)=>q.active).map((q)=>q.category))]:[],review:detail?.reviews?.[0]??null};}); }
export function filterDirectory(items: DirectoryItem[], search: string, kind: 'all'|'standard'|'custom', status: 'all'|InstrumentStatus, visibility: 'all'|'visible'|'archived'='all') { const term=search.trim().toLocaleLowerCase();return items.filter(({instrument,version})=>(!term||instrument.name.toLocaleLowerCase().includes(term)||instrument.code.toLocaleLowerCase().includes(term))&&(kind==='all'||instrument.instrument_kind===kind)&&(status==='all'||version?.status===status)&&(visibility==='all'||(visibility==='visible'?instrument.active&&version?.status!=='archived':!instrument.active||version?.status==='archived'))); }
export function isEditable(detail: InstrumentDetail) { return detail.version.status==='draft'; }
export function currentReview(detail: InstrumentDetail) { return detail.reviews?.find((review)=>review.definition_revision===detail.version.definition_revision)??null; }
export function canPublish(detail: InstrumentDetail, validation: {publishable:boolean}|null) { return detail.version.status==='draft'&&validation?.publishable===true&&currentReview(detail)?.status==='approved'; }
export function renumberQuestions(questions: QuestionDraft[]) { return questions.map((question,index)=>({...question,position:index+1,options:question.options.map((option,optionIndex)=>({...option,position:optionIndex}))})); }
export function moveQuestion(questions: QuestionDraft[], index: number, direction: -1|1) { const target=index+direction;if(target<0||target>=questions.length)return questions;const next=[...questions];[next[index],next[target]]=[next[target],next[index]];return renumberQuestions(next); }
export function addQuestion(questions: QuestionDraft[]): QuestionDraft[] { return [...questions,{item_key:`ITEM-${String(questions.length+1).padStart(2,'0')}`,category:'depression',position:questions.length+1,wording:'',active:true,options:[{position:0,label:'',score:0},{position:1,label:'',score:1}]}]; }
export function validateDraft(questions: QuestionDraft[]) { const issues:string[]=[];const keys=new Set<string>();if(!questions.length)issues.push('questions');questions.forEach((q)=>{const key=q.item_key.trim().toLocaleLowerCase();if(!q.item_key.trim()||!q.wording.trim()||!/^[A-Za-z0-9_-]+$/.test(q.item_key))issues.push('question');if(keys.has(key))issues.push('duplicateKey');keys.add(key);if(q.options.length<2||q.options.some((o)=>!o.label.trim()||!Number.isInteger(o.score)||o.score<0||o.score>100))issues.push('options');});return [...new Set(issues)]; }
export function newLocalDraft(): LocalInstrumentDraft { return {code:'',name:'',description:'',language:'id',dimensions:[],questions:[]}; }
export function localDraftCompleteness(draft: LocalInstrumentDraft) { const codes=new Set(draft.dimensions);return {metadata:/^[A-Za-z0-9_-]{3,40}$/.test(draft.code)&&!!draft.name.trim()&&!!draft.description.trim(),dimensions:draft.dimensions.length>0&&codes.size===draft.dimensions.length&&draft.dimensions.every(x=>/^[a-z][a-z0-9_-]{0,59}$/.test(x)),questions:validateDraft(draft.questions).length===0&&draft.questions.every(q=>codes.has(q.category))}; }
export function statusTone(status: InstrumentStatus): 'info'|'success'|'neutral' { return status==='draft'?'info':status==='published'?'success':'neutral'; }
