import assert from 'node:assert/strict';
import test from 'node:test';
import { addQuestion, canPublish, currentReview, filterDirectory, isEditable, latestVersion, localDraftCompleteness, moveQuestion, newLocalDraft, normalizeDirectory, validateDraft } from './model.ts';
import type { Instrument, InstrumentDetail, QuestionDraft } from './types.ts';

const instrument: Instrument={instrument_id:'i',code:'CUSTOM',name:'Wellbeing',description:null,active:true,language:'Bahasa Indonesia',instrument_kind:'custom',derived_from_instrument_id:null,norms_enabled:false,provenance:{},versions:[{instrument_version_id:'v1',version_number:1,status:'published',authoritative_config:true,updated_at:'2026-01-01',published_at:'2026-01-01'},{instrument_version_id:'v2',version_number:2,status:'draft',authoritative_config:false,updated_at:'2026-02-01',published_at:null}]};
const questions:QuestionDraft[]=[{item_key:'A',category:'stress',position:1,wording:'A?',active:true,options:[{position:0,label:'No',score:0},{position:1,label:'Yes',score:1}]},{item_key:'B',category:'anxiety',position:2,wording:'B?',active:true,options:[{position:0,label:'Low',score:0},{position:1,label:'High',score:2}]}];
test('latest version follows server version number',()=>assert.equal(latestVersion(instrument)?.instrument_version_id,'v2'));
test('normalization preserves category and option order',()=>{const details=new Map<string,InstrumentDetail>([['v2',{version:{...instrument.versions[1],instrument_id:'i',code:'CUSTOM',name:'Wellbeing',language:'Bahasa Indonesia',instrument_kind:'custom',norms_enabled:false,provenance:{},derived_from_instrument_id:null,expected_question_count:2,definition_revision:1,scoring_config:null,created_at:'',created_by_name:null,updated_by_name:null,published_by_name:null},questions}]]);const row=normalizeDirectory([instrument],details)[0];assert.deepEqual(row.categories,['stress','anxiety']);assert.equal(row.questionCount,2);});
test('directory search only checks name and code',()=>{const row={instrument,version:latestVersion(instrument),questionCount:2,categories:[],review:null};assert.equal(filterDirectory([row],'well','all','all').length,1);assert.equal(filterDirectory([row],'question text','all','all').length,0);});
test('all draft definitions are editable while published versions stay immutable',()=>{const detail={version:{...instrument.versions[1],instrument_id:'i',code:'',name:'',language:null,instrument_kind:'custom' as const,norms_enabled:false,provenance:{},derived_from_instrument_id:null,expected_question_count:2,definition_revision:1,scoring_config:null,created_at:'',created_by_name:null,updated_by_name:null,published_by_name:null},questions};assert.equal(isEditable(detail),true);assert.equal(isEditable({...detail,version:{...detail.version,status:'published'}}),false);assert.equal(isEditable({...detail,version:{...detail.version,instrument_kind:'standard'}}),true);});
test('reordering is deterministic and keeps options ordered',()=>{const moved=moveQuestion(questions,1,-1);assert.deepEqual(moved.map((q)=>[q.item_key,q.position]),[['B',1],['A',2]]);assert.deepEqual(moved[0].options.map((o)=>o.position),[0,1]);});
test('new questions start with two explicit score options',()=>assert.deepEqual(addQuestion([])[0].options.map((o)=>o.score),[0,1]));
test('draft validation rejects duplicate keys and incomplete options',()=>assert.deepEqual(validateDraft([...questions,{...questions[0],position:3,options:[]}]).sort(),['duplicateKey','options']));
test('custom draft starts without DASS dimensions or scoring',()=>{const draft=newLocalDraft();assert.deepEqual(draft.dimensions,[]);assert.deepEqual(draft.questions,[]);});
test('completeness requires code, metadata, matching dimensions, and valid questions',()=>{const draft={...newLocalDraft(),code:'CUSTOM',name:'A',description:'B',dimensions:['stress','anxiety'],questions};assert.deepEqual(localDraftCompleteness(draft),{metadata:true,dimensions:true,questions:true});});
test('publish gate accepts only an approval for the current definition revision',()=>{const detail:InstrumentDetail={version:{...instrument.versions[1],instrument_id:'i',code:'CUSTOM',name:'Wellbeing',language:'en',instrument_kind:'custom',norms_enabled:false,provenance:{},derived_from_instrument_id:null,expected_question_count:2,definition_revision:2,scoring_config:null,created_at:'',created_by_name:null,updated_by_name:null,published_by_name:null},questions,reviews:[{review_id:'old',definition_revision:1,status:'approved'},{review_id:'current',definition_revision:2,status:'approved'}]};assert.equal(currentReview(detail)?.review_id,'current');assert.equal(canPublish(detail,{publishable:true}),true);assert.equal(canPublish({...detail,reviews:[detail.reviews![0]]},{publishable:true}),false);assert.equal(canPublish(detail,{publishable:false}),false);});
