#!/usr/bin/env bun
// Organic profile warmer for BetterWright's persistent browser profile.
//
// Tools that attach to a real user's daily-driver Chrome get anti-bot strength
// for free, from an aged, signed-in profile. BetterWright deliberately cannot
// attach to a real Chrome (connectOverCdp is rejected), but its profile persists
// history, cookies, storage, and logins across runs — so the equivalent is to
// *age that profile on purpose* with organic, human-shaped browsing before and
// alongside real tasking.
//
// What one warming run accumulates into the persistent profile:
//   - browser history with realistic depth (multi-hop same-origin link walks)
//   - first-party cookies, localStorage, IndexedDB, cache, service workers
//   - behavioral telemetry generated by the human.* primitives (Bézier
//     pointer, paced dwell, eased scrolling) rather than raw CDP input
//   - continued liveness of any signed-in sessions (run `betterwright run
//     --headed` once and sign in manually; warming keeps those cookies fresh)
//
// Guardrails honored by design:
//   - no public search-engine SERP automation (BetterWright policy blocks it)
//   - bounded dwells and hop counts; this is profile maintenance, not scraping
//
// Usage:
//   bun research/warm-profile.ts [--minutes 20] [--session warm] [--max-hops 6]
//
// Recommended cadence: 2×20 min on day 0 (plus the one-time headed manual
// sign-in to your real accounts), then 15–30 min daily for ~2 weeks, then
// 3×/week maintenance. Always warm the SAME persistent profile you later task
// — deleting $BETTERWRIGHT_HOME/browser/profile resets the pinned fingerprint
// seed and all accumulated age.

import fs from "node:fs";
import path from "node:path";
import { BetterWright } from "../dist/src/index.js";

const args = process.argv.slice(2);
function argValue(name, fallback) {
  const index = args.indexOf(`--${name}`);
  if (index === -1 || index + 1 >= args.length) return fallback;
  return args[index + 1];
}

const MINUTES = Math.max(1, Number(argValue("minutes", 20)) || 20);
const SESSION = String(argValue("session", "warm"));
const MAX_HOPS = Math.max(2, Math.min(10, Number(argValue("max-hops", 6)) || 6));
const HOME = process.env.BETTERWRIGHT_HOME || path.join(process.env.HOME || ".", ".betterwright");
const LOG_FILE = path.join(HOME, "warm-log.json");

// Reputable, automation-tolerant seeds chosen for deep same-origin link graphs.
// Deliberately no search engines: public SERP automation is disabled by policy.
const SEED_SITES = [
  "https://en.wikipedia.org/wiki/Main_Page",
  "https://www.bbc.com/news",
  "https://www.reuters.com/world/",
  "https://stackoverflow.com/questions",
  "https://developer.mozilla.org/en-US/docs/Web",
  "https://www.npmjs.com/package/playwright-core",
  "https://github.com/explore",
  "https://arxiv.org/list/cs/recent",
  "https://www.imdb.com/chart/top/",
  "https://www.weather.com/",
  "https://news.ycombinator.com/",
  "https://www.npr.org/sections/news/",
];

function loadLog() {
  try {
    const parsed = JSON.parse(fs.readFileSync(LOG_FILE, "utf8"));
    return {
      visited: new Set(Array.isArray(parsed.visited) ? parsed.visited : []),
      runs: Number(parsed.runs) || 0,
    };
  } catch {
    return { visited: new Set(), runs: 0 };
  }
}

function saveLog(log) {
  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });
  const visited = [...log.visited].slice(-20_000); // cap; recency beats completeness
  fs.writeFileSync(LOG_FILE, JSON.stringify({ visited, runs: log.runs }, null, 2));
}

// One batch = open a seed, then walk MAX_HOPS same-origin links with
// human-shaped scrolling and dwell. Runs inside the sandbox: Playwright page
// API + human.* + page.waitForTimeout only (no fs/process in snippet scope).
function batchSnippet(seedUrl, maxHops) {
  return `
    const visited = [];
    const rand = (min, max) => min + Math.random() * (max - min);
    try {
      await page.goto(${JSON.stringify(seedUrl)}, { waitUntil: "domcontentloaded", timeout: 30000 });
    } catch (error) {
      return { visited, note: "seed navigation failed: " + String(error).slice(0, 120) };
    }
    for (let hop = 0; hop < ${maxHops}; hop += 1) {
      // Read like a human: a few eased scrolls with dwell between them.
      const scrolls = 2 + Math.floor(rand(0, 3));
      for (let s = 0; s < scrolls; s += 1) {
        try { await human.scroll(Math.round(rand(320, 880))); } catch {}
        await page.waitForTimeout(rand(1200, 3800));
      }
      visited.push(page.url());
      // Harvest same-origin links via protocol calls (no function args cross
      // the sandbox realm), then click one with the Bézier human pointer.
      let picked = null;
      try {
        const links = page.locator("a[href]");
        const count = Math.min(await links.count(), 60);
        const origin = new URL(page.url()).origin;
        const candidates = [];
        for (let i = 0; i < count; i += 1) {
          const item = links.nth(i);
          const href = await item.getAttribute("href").catch(() => null);
          if (!href || href.startsWith("#") || href.startsWith("mailto:")) continue;
          let absolute = null;
          try { absolute = new URL(href, page.url()); } catch { continue; }
          if (absolute.origin !== origin) continue;
          if (!/^(http|https):$/.test(absolute.protocol)) continue;
          if (!(await item.isVisible().catch(() => false))) continue;
          candidates.push({ index: i, url: absolute.href });
        }
        if (candidates.length) picked = candidates[Math.floor(rand(0, candidates.length))];
        if (picked) await human.click(links.nth(picked.index));
      } catch {}
      await page.waitForTimeout(rand(2500, 6500)); // post-click dwell
      if (!picked) break;
    }
    return { visited, note: "ok" };
  `;
}

async function main() {
  const log = loadLog();
  log.runs += 1;
  const deadline = Date.now() + MINUTES * 60_000;
  const bw = new BetterWright();
  let batch = 0;

  console.log(
    `[warm] session=${SESSION} minutes=${MINUTES} run #${log.runs} ` +
      `(${log.visited.size} urls seen historically)`,
  );

  try {
    while (Date.now() < deadline) {
      batch += 1;
      // Prefer seeds we have not walked recently; fall back to any once exhausted.
      const fresh = SEED_SITES.filter((site) => !log.visited.has(site));
      const pool = fresh.length ? fresh : SEED_SITES;
      const seed = pool[Math.floor(Math.random() * pool.length)];

      const result = await bw.run(batchSnippet(seed, MAX_HOPS), { session: SESSION });
      if (!result.ok) {
        console.log(`[warm] batch ${batch}: ${String(result.error).slice(0, 140)}`);
      } else {
        const visited = result.result?.visited || [];
        for (const url of visited) log.visited.add(url);
        log.visited.add(seed);
        console.log(
          `[warm] batch ${batch}: ${seed} -> ${visited.length} page(s) ` +
            `(${result.durationMs}ms)`,
        );
      }
      saveLog(log);

      // Between-batch idle: humans do not chain reading sessions back to back.
      const idleMs = 20_000 + Math.random() * 70_000;
      if (Date.now() + idleMs > deadline) break;
      await new Promise((resolve) => setTimeout(resolve, idleMs));
    }
  } finally {
    await bw.close().catch(() => {});
    saveLog(log);
  }

  console.log(`[warm] done. profile now knows ${log.visited.size} urls over ${log.runs} run(s).`);
}

main().catch((error) => {
  console.error(`[warm] fatal: ${error?.stack || error}`);
  process.exitCode = 1;
});
